// Case definitions (42 crates: id, name, price, contents, odds) extracted from data.js

export const cases = [{
    id: `crate_valve_1`,
    name: `Arms Deal Case`,
    set: `set_weapons_i`,
    decal: `armsdeal1`,
    rare: ``,
    nameKey: `CSGO_set_weapons_i`,
    price: 250,
    icon: `crate_valve_1`,
    mesh: `csgo`,
    items: `ak47_ak47_autoexec_camo.ak47_ak47_crane_flight.ak47_aq_oiled.ak47_cu_ak-47_phantom_disruptor.ak47_cu_graphic_overlay_ak47.ak47_cu_green_leather_ak47.ak47_cu_overpass_monster_ak47.ak47_gs_ak47_strone.ak47_hy_ak47lam_bw.ak47_hy_ak47lam_green.ak47_soe_metallic_green_2.aug_aa_fade_metallic.aug_an_navy_bravo.aug_hy_feathers_aug.awp_am_lightning_awp.bizon_bizon_traitor.deagle_aa_vertigo.deagle_cu_overpass_aqua_deagle.famas_hye_firework_patches_famas.galil_hy_forest_winter.glock_am_dragon_glock.glock_so_sand_bravo.m4a1s_am_zebra_dark.m4a4_cu_m4a1_howling.mac10_sp_twigs_beach.mp7_hy_skulls.mp7_mp7_binary_green.nova_am_oval_hex.p250_aa_vertigogeo_neon.p90_cu_poly_violet_p90.sawedoff_cu_green_leather_sawedoff.sg553_gs_happy_red_sg556.sg553_so_purple.tec9_cu_tec9_mummy.ump45_hy_varicamo_red.usps_am_zebra_dark.xm1014_ht_shapes_xm1014`.split(`.`),
    authentic: [`ak47_aq_oiled`, `aug_hy_feathers_aug`, `awp_am_lightning_awp`, `deagle_aa_vertigo`, `glock_am_dragon_glock`, `m4a1s_am_zebra_dark`, `mp7_hy_skulls`, `sg553_so_purple`, `usps_am_zebra_dark`]
  }, {
    id: `crate_esports_2013`,
    name: `eSports 2013 Case`,
    set: `set_esports`,
    decal: ``,
    rare: ``,
    nameKey: `CSGO_set_esports`,
    price: 250,
    icon: `crate_esports_2013`,
    mesh: ``,
    items: `ak47_ak47_jinn_consequence.ak47_am_bamboo_jungle.ak47_cu_pinstripe_ak47.ak47_gs_ak47_gold_arabesque.ak47_hy_ak47lam.ak47_hy_mesh_safetyorange.aug_an_red.aug_aug_ghost_signal.aug_aug_trigger_discipline_velco.aug_hy_copperhead.aug_soe_aug_creep.awp_gs_awp_strone.awp_hy_blam_simple.awp_hy_nuclear_skulls_redblue.bizon_cu_bizon_Curse.deagle_deagle_eastern_enigma_blue.famas_hy_doomkitty.famas_so_space_marine.galil_hy_ddpat_orange.galil_hy_nuclear_skulls_aqua.glock_sp_tire_tread_red.m4a4_cu_m4a4_train_hell.m4a4_sp_zebracam_bw.mag7_am_carbon_fiber.mag7_hy_icosahedron.mp7_mp7_smoking_kills_v2.nova_am_veneto2.p250_am_ren_dark.p250_sp_splash_p250.p90_cu_catskulls_p90.p90_ht_simple_camo.sawedoff_gsch_ripple.sawedoff_hy_ddpat_orange.sg553_ht_orange_basket.tec9_gs_tec9_envoy.ump45_hye_test_animal_print_45.xm1014_hy_cloud_camo`.split(`.`),
    authentic: [`ak47_hy_ak47lam`, `awp_hy_blam_simple`, `famas_hy_doomkitty`, `galil_hy_ddpat_orange`, `m4a4_sp_zebracam_bw`, `mag7_hy_icosahedron`, `p250_sp_splash_p250`, `p90_cu_catskulls_p90`, `sawedoff_hy_ddpat_orange`]
  }, {
    id: `crate_valve_2`,
    name: `Arms Deal 2 Case`,
    set: `set_weapons_ii`,
    decal: `armsdeal2`,
    rare: ``,
    nameKey: `CSGO_set_weapons_ii`,
    price: 250,
    icon: `crate_valve_2`,
    mesh: `csgo`,
    items: `ak47_ak47_puffer_custom.ak47_cu_well_traveled_ak47.ak47_gsch_ak_djiin.ak47_hye_zeds.awp_hy_varicamo_red.awp_hy_varicamo_simple_yellow.awp_sp_snake.bizon_aq_brass.bizon_aq_steel_bravo.bizon_hy_bamboo_jungle_ink.deagle_deagle_firebreathing.dualies_am_ossify_red.famas_hy_bluehex.famas_soe_bw_blast.fiveseven_aq_oiled.galil_hy_ruins_red.glock_spe_missile.m4a1s_hy_redtiger.m4a4_cu_poseidon.mag7_am_chainmail.mp7_so_mustard.mp9_aa_vertigo.nova_am_crumple.nova_an_silver.p250_am_urban.p250_hy_redhex.p90_am_slither_p90.p90_hy_blueprint_aqua.sawedoff_hy_ali_tile_bravo.scar20_hy_webs_darker.sg553_hye_animal_print_lc.ssg08_cu_shark.tec9_an_titanium30v.tec9_hy_ancient_tiles_peach.ump45_so_caramel.usps_am_electric_red.xm1014_hy_ddpat_urb`.split(`.`),
    authentic: [`dualies_am_ossify_red`, `famas_hy_bluehex`, `fiveseven_aq_oiled`, `m4a1s_hy_redtiger`, `mp9_aa_vertigo`, `nova_am_crumple`, `p250_hy_redhex`, `p90_am_slither_p90`, `scar20_hy_webs_darker`, `ssg08_cu_shark`, `tec9_an_titanium30v`, `usps_am_electric_red`]
  }, {
    id: `crate_operation_ii`,
    name: `Operation Bravo Case`,
    set: `set_bravo_i`,
    decal: `bravo`,
    rare: ``,
    nameKey: `CSGO_set_bravo_i`,
    price: 250,
    icon: `crate_operation_ii`,
    mesh: `csgo`,
    items: `ak47_cu_fireserpent_ak47_bravo.ak47_ht_poly_camo_ak47.ak47_soe_iridescent_purple.awp_am_crumple_bravo.bizon_bizon_rmx.bizon_hy_blueprint_white.bizon_hy_hunter_modern.bizon_so_orca.cz75_am_crystallized_green.deagle_am_scales_bravo.deagle_gs_deagle_fennec.dualies_cu_season_elites_bravo.famas_soo_famas_grey_ghost.g3sg1_hy_bluepolygon_bravo.galil_hy_crumple_bravo.galil_hy_varicamo.m249_cu_m249_scarab.m4a1s_hy_ocean_bravo.m4a4_gs_m4a4_coalition.m4a4_sp_star_bravo.mac10_aq_etched_mac10_bravo.mag7_am_navy_shine.mp7_so_olive_bravo.nova_aq_steel.nova_hy_seaside_bravo.p2000_am_ossify_blue_p2000_bravo.p250_brutalist_architecture.p90_cu_dragon_p90_bravo.p90_hy_ddpat_desert.sawedoff_hy_bamboo_jungle_black.sg553_so_red_sg553.sg553_sp_spray_waves_bravo.tec9_hy_bamboo_jungle.ump45_so_indigo_and_grey.ump45_sp_skull_diagram_bravo.usps_hy_siege_bravo.xm1014_hy_hunter_blaze_orange`.split(`.`),
    authentic: [`ak47_cu_fireserpent_ak47_bravo`, `awp_am_crumple_bravo`, `deagle_am_scales_bravo`, `dualies_cu_season_elites_bravo`, `g3sg1_hy_bluepolygon_bravo`, `galil_hy_crumple_bravo`, `m4a1s_hy_ocean_bravo`, `m4a4_sp_star_bravo`, `mac10_aq_etched_mac10_bravo`, `nova_hy_seaside_bravo`, `p2000_am_ossify_blue_p2000_bravo`, `p90_cu_dragon_p90_bravo`, `sg553_sp_spray_waves_bravo`, `ump45_sp_skull_diagram_bravo`, `usps_hy_siege_bravo`]
  }, {
    id: `crate_esports_2013_winter`,
    name: `eSports 2013 Winter Case`,
    set: `set_esports_ii`,
    decal: ``,
    rare: ``,
    nameKey: `CSGO_set_esports_ii`,
    price: 250,
    icon: `crate_esports_2013_14`,
    mesh: ``,
    items: `ak47_cu_ak_island_floral.ak47_hy_ak47lam_blue.ak47_hy_veneto_purple.aug_am_bloom_blue.aug_am_circuitboard_orange.aug_am_jorm_orange.awp_hy_hive.bizon_hy_lizard_skin.bizon_hy_water_crest.cz75_an_emerald.cz75_so_orange_accents2.cz75_so_orca.deagle_am_crystallized_dark.deagle_am_ddpatdense_peacock.deagle_hy_ddpat_urb.famas_cu_broken_path_famas.famas_sp_knots_blue.fiveseven_hy_flowers.g3sg1_sp_zebracam_blue.galil_an_titanium30v.galil_hy_varicamo_urban.m249_ht_peaks_rainbow.m4a4_cu_xray_m4.m4a4_gs_m4a4_ra.mag7_am_urban.mp7_sp_dapple.nova_cu_walnut_nova.nova_sp_camo_wood_blue.p250_am_ddpatdense_silver.p250_cu_money.p90_hy_forest_night.p90_hy_modspots.sawedoff_hy_ddpat.sg553_so_tornado.tec9_hy_ddpat_urb.ump45_soch_hueshift_desat.xm1014_hy_leaf_green`.split(`.`),
    authentic: [`ak47_hy_ak47lam_blue`, `awp_hy_hive`, `bizon_hy_water_crest`, `deagle_am_ddpatdense_peacock`, `famas_cu_broken_path_famas`, `fiveseven_hy_flowers`, `g3sg1_sp_zebracam_blue`, `galil_an_titanium30v`, `m4a4_cu_xray_m4`, `nova_sp_camo_wood_blue`, `p250_am_ddpatdense_silver`, `p90_hy_modspots`]
  }, {
    id: `crate_community_1`,
    name: `Winter Offensive Weapon Case`,
    set: `set_community_1`,
    decal: `winteroffensive`,
    rare: ``,
    nameKey: `CSGO_set_community_1`,
    price: 250,
    icon: `crate_community_1`,
    mesh: `csgo`,
    items: `ak47_hye_ak47_nouveau.ak47_soe_varicamo.aug_aug_lapis_lazuli.awp_cu_awp_cobra.bizon_am_turqoise_halftone.bizon_hy_nerodia.deagle_am_heist_plans_purple.deagle_ht_earth_fans.deagle_hy_mottled_sand.deagle_hy_varicamo_urban.deagle_hye_car_wrap.deagle_sp_spacerace_blue.dualies_an_emerald.dualies_hy_marina_sunrise.famas_cu_famas_pulse.famas_sp_spitfire_famas_bravo.fiveseven_hy_kami.galil_cu_sandstorm.galil_hye_yellow_usaf.m249_aq_obsidian.m249_hy_blizzard.m4a4_cu_m4_asimov.m4a4_ht_metal_edges.mag7_an_silver.mp7_sp_labyrinth.mp9_am_thorny_rose_mp9.nova_cu_skull_nova.nova_gs_nova_sobek.p250_cu_p250_refined.p250_cu_xray_p250.p90_hy_usaf_round.sawedoff_cu_sawedoff_octopump.sawedoff_hy_desert_bloom.sg553_so_yellow.tec9_hy_geometric_steps_yellow.ump45_sp_dapple.xm1014_hy_varicamo_blue`.split(`.`),
    authentic: [`awp_cu_awp_cobra`, `bizon_am_turqoise_halftone`, `dualies_hy_marina_sunrise`, `famas_cu_famas_pulse`, `fiveseven_hy_kami`, `galil_cu_sandstorm`, `m249_aq_obsidian`, `m4a4_cu_m4_asimov`, `mp9_am_thorny_rose_mp9`, `nova_cu_skull_nova`, `p250_cu_p250_refined`, `sawedoff_cu_sawedoff_octopump`]
  }, {
    id: `crate_valve_3`,
    name: `Arms Deal 3 Case`,
    set: `set_weapons_iii`,
    decal: `armsdeal3`,
    rare: ``,
    nameKey: `CSGO_set_weapons_iii`,
    price: 250,
    icon: `crate_valve_3`,
    mesh: `csgo`,
    items: `ak47_cu_ak_jaguar.ak47_sp_mesh_tan.aug_cu_overpass_graf_aug.aug_gs_lilpig_aug.bizon_hy_varicamo_night.cz75_am_diamond_plate.cz75_am_fuschia.cz75_aq_etched_cz75.cz75_hy_webs.deagle_aq_engraved_deagle.deagle_so_night.dualies_an_navy.dualies_so_panther.famas_famas_snake_song.famas_gs_train_car_famas.famas_soe_blue_famas.famas_sp_mesh_hot_and_cold.famas_sp_spray.fiveseven_am_copper_flecks.galil_so_green.glock_hy_craquelure.m249_hy_ddpat_jungle_bravo.m4a4_hy_ddpat_urb.mag7_aq_steel.mp7_sp_spray_army.nova_hy_ducts_grey.p2000_hy_poly_camo.p250_am_p250_beaded_paint.p250_gs_p250_apep.p90_hy_vertigogeo.sawedoff_hy_tigers_tan.sg553_soo_blues.tec9_am_fluted_tec9.tec9_hy_hades.ump45_sp_nukestripe_maroon.usps_aq_usp_stainless.xm1014_hy_varicamo_desert`.split(`.`),
    authentic: [`cz75_am_diamond_plate`, `cz75_am_fuschia`, `cz75_aq_etched_cz75`, `cz75_hy_webs`, `deagle_aq_engraved_deagle`, `dualies_so_panther`, `fiveseven_am_copper_flecks`, `glock_hy_craquelure`, `p2000_hy_poly_camo`, `p250_am_p250_beaded_paint`, `tec9_am_fluted_tec9`, `usps_aq_usp_stainless`]
  }, {
    id: `crate_community_2`,
    name: `Operation Phoenix Weapon Case`,
    set: `set_community_2`,
    decal: `phoenix`,
    rare: ``,
    nameKey: `CSGO_set_community_2`,
    price: 250,
    icon: `crate_community_2`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_cobra.ak47_sp_spray_jungle.aug_cu_aug_chameleonaire.aug_gs_aug_sand_storm.awp_cu_awp_asimov.bizon_hy_wood_grain_camo_red.deagle_soe_plum.famas_an_famas_sgt.famas_sp_palm_sunset.famas_spo_palm.fiveseven_aa_fade_metallic.fiveseven_am_crystallized_silver.fiveseven_fiveseven_polymer_dark.fiveseven_hy_bud_red.fiveseven_so_orange_accents.galil_so_tornado.m249_hy_zodiac3.m4a4_hy_ddpat_urban_red.mac10_cu_mac10_redhot.mag7_aq_steel_inferno.mag7_cu_mag7_heaven.mp7_sp_tape_orange.negev_sp_negev_turq_terrain.nova_cu_nova_antique.nova_hy_torn_camo_paints.p250_gs_p250_checker.p90_cu_p90_trigon.p90_hye_abstract_knot.sawedoff_hy_varicamo_red.sg553_cu_sg553_pulse.sg553_sp_asgard_wall.tec9_cu_tec9_sandstorm.tec9_hy_mesh_safetyorange.ump45_cu_ump_corporal.ump45_sp_ump45_d-visions.usps_cu_usp_elegant.xm1014_hye_drippy_camo`.split(`.`),
    authentic: [`ak47_cu_ak47_cobra`, `aug_cu_aug_chameleonaire`, `awp_cu_awp_asimov`, `famas_an_famas_sgt`, `mac10_cu_mac10_redhot`, `mag7_cu_mag7_heaven`, `negev_sp_negev_turq_terrain`, `nova_cu_nova_antique`, `p90_cu_p90_trigon`, `sg553_cu_sg553_pulse`, `tec9_cu_tec9_sandstorm`, `ump45_cu_ump_corporal`, `usps_cu_usp_elegant`]
  }, {
    id: `crate_community_3`,
    name: `Huntsman Weapon Case`,
    set: `set_community_3`,
    decal: `huntsman`,
    rare: `crate_community_3`,
    nameKey: `CSGO_set_community_3`,
    price: 250,
    icon: `crate_community_3`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_rubber.ak47_sp_zebracam.aug_cu_aug_progressiv.awp_am_tigers_blue.bizon_cu_bizon_antique.bizon_hye_car_wrap_bizon.cz75_am_gyrate.cz75_am_nitrogen.dualies_am_crystallized_blue.dualies_cu_retribution.fiveseven_aa_fade_red_blue.fiveseven_soe_pink_cranes.galil_hy_galil_kami.galil_soch_blorb_bw_galilar.m249_hye_m249_car_wrap_3.m4a4_cu_titanstorm.m4a4_hy_desert.mac10_cu_korupt.mac10_cu_mac10_decay.mag7_gs_mag7_glass.mp7_sp_zebracam_red.nova_hy_vertigoillusion_yellow.p2000_cu_p2000_pulse.p250_hy_blueprint_red.p90_an_royalbleed.p90_cu_p90_scorpius.p90_hye_coral.sawedoff_hye_batik_eyes.scar20_cu_scar_cyrex.sg553_sp_desert_skulls.ssg08_cu_ssg08_immortal.tec9_cu_tec9_asiimov.tec9_hy_murano_orange.ump45_ump45_illumina_v2.usps_cu_kaiman.usps_cu_usp_spitfire.xm1014_cu_xm1014_heaven_guard.xm1014_so_grassland`.split(`.`),
    authentic: [`ak47_cu_ak47_rubber`, `aug_cu_aug_progressiv`, `bizon_cu_bizon_antique`, `cz75_am_gyrate`, `cz75_am_nitrogen`, `dualies_cu_retribution`, `galil_hy_galil_kami`, `m4a4_cu_titanstorm`, `mac10_cu_korupt`, `mac10_cu_mac10_decay`, `p2000_cu_p2000_pulse`, `p90_an_royalbleed`, `p90_cu_p90_scorpius`, `scar20_cu_scar_cyrex`, `ssg08_cu_ssg08_immortal`, `tec9_cu_tec9_asiimov`, `usps_cu_kaiman`, `usps_cu_usp_spitfire`, `xm1014_cu_xm1014_heaven_guard`]
  }, {
    id: `crate_community_4`,
    name: `Operation Breakout Weapon Case`,
    set: `set_community_4`,
    decal: `breakout`,
    rare: `crate_community_4`,
    nameKey: `CSGO_set_community_4`,
    price: 250,
    icon: `crate_community_4`,
    mesh: `csgo`,
    items: `ak47_cu_ak_xray.aug_am_carbon_fiber.awp_awp_black_box.awp_awp_ice_coaled.awp_hy_ddpat_pink.awp_hy_snakeskin.bizon_hye_geobirds_sunrise.deagle_cu_deagle_aureus.dualies_am_heist_plans_green.fiveseven_an_gunmetal_bravo.fiveseven_aq_57_feathers.g3sg1_am_murano_violet.g3sg1_sp_moro_carving_lightblue.galil_aa_fade_metallic.galil_am_geometric_steps.galil_cu_galil_ar-camo.galil_hye_earth_mandala.galil_soe_orange_flick.m249_hyo_jungle_desat.m4a1s_cu_m4a1s_cyrex.m4a4_hy_hunter_modern.mag7_hy_geometric_steps_pearl.mp9_am_army_shine.negev_cu_negev_titanstorm.nova_cu_nova_koi.nova_hy_zodiac1.p2000_cu_p2000_ivory.p250_cu_bittersweet.p250_hy_crumple_dark_bravo.p90_hye_zoom.sawedoff_sawedoff_fusion.sg553_sp_mesh_python.ssg08_aq_leviathan.tec9_hy_nuclear_skulls5_tec9.ump45_hy_lines_orange.ump45_ump_fragment.xm1014_so_jungle_bravo`.split(`.`),
    authentic: [`deagle_cu_deagle_aureus`, `fiveseven_aq_57_feathers`, `m4a1s_cu_m4a1s_cyrex`, `negev_cu_negev_titanstorm`, `nova_cu_nova_koi`, `p2000_cu_p2000_ivory`, `p250_cu_bittersweet`, `ssg08_aq_leviathan`, `ump45_hy_lines_orange`]
  }, {
    id: `crate_esports_2014_summer`,
    name: `eSports 2014 Summer Case`,
    set: `set_esports_iii`,
    decal: ``,
    rare: ``,
    nameKey: `CSGO_set_esports_iii`,
    price: 250,
    icon: `crate_esports_2014_summer`,
    mesh: ``,
    items: `ak47_cu_panther_ak47.aug_am_intelligence_grey.aug_hy_tiger.awp_cu_favela_awp.bizon_hy_splatter.bizon_so_aqua_stmarc.cz75_hy_bluehex.deagle_hy_webs_darker.dualies_aq_forced.fiveseven_aq_case_hardened_fiveseven.galil_so_orca.galil_soe_robinsegg.galil_sp_overpass_paint_pen_metal.glock_am_ddpatdense_silver.glock_am_nuclear_pattern1_glock.glock_glock_train_green.m249_so_jungle.m4a4_cu_bullet_rain_m4a1.m4a4_hy_v_tiger.mac10_so_purple.mag7_hy_nuclear_hotorange.mp7_am_ossify_blue.mp9_am_stained_glass.negev_cu_bratatat_negev.nova_cu_spring_nova.nova_hye_geobirds.p2000_cu_favela_p2000.p250_hy_desert_multicam.p90_hy_zombie.p90_p90_deathgaze.sawedoff_sawedoff_lunar_wyrm.sg553_sp_nukestripe_maroon_sg553.ssg08_am_zebra_dark.tec9_hy_phoenix_tags_lilac.ump45_ump_transit.usps_hy_redtiger.xm1014_hy_snakeskin_red.xm1014_so_moss`.split(`.`),
    authentic: [`ak47_cu_panther_ak47`, `aug_hy_tiger`, `awp_cu_favela_awp`, `bizon_hy_splatter`, `cz75_hy_bluehex`, `deagle_hy_webs_darker`, `glock_am_ddpatdense_silver`, `m4a4_cu_bullet_rain_m4a1`, `mac10_so_purple`, `mp7_am_ossify_blue`, `negev_cu_bratatat_negev`, `nova_cu_spring_nova`, `p2000_cu_favela_p2000`, `p90_hy_zombie`, `ssg08_am_zebra_dark`, `usps_hy_redtiger`, `xm1014_hy_snakeskin_red`]
  }, {
    id: `crate_operation_vanguard`,
    name: `Operation Vanguard Weapon Case`,
    set: `set_community_5`,
    decal: `vanguard`,
    rare: ``,
    nameKey: `CSGO_set_community_5`,
    price: 250,
    icon: `crate_community_5`,
    mesh: `csgo`,
    items: `ak47_cu_tribute_ak47.aug_am_jade.awp_hy_technowar_rwb.bizon_so_grey_nuclear_green_bizon.dualies_cu_dual_elites_rally.fiveseven_cu_fiveseven_urban_hazard.fiveseven_cu_vertigo_fiveseven.g3sg1_am_g3sg1_murky.galil_sp_galil_caution.glock_aq_glock_coiled.glock_hy_overpass_tagged_teal.glock_so_red.glock_soe_roses.m249_m249_blocks_purple.m249_so_keycolors.m249_sp_moro_carving_burnt.m4a1s_aq_m4a1s_basilisk.m4a1s_hy_hexagon.m4a4_cu_m4a4_griffin.m4a4_hye_abstract_knot_m4.mag7_so_aqua.mag7_sp_mag7_firebitten.mp9_cu_mp9_chevron.mp9_cu_mp9_island_floral.nova_nova_morning_sun.p2000_cu_p2000_fire_elemental.p250_aq_p250_cartel.p250_hy_ducts_blue.p90_p90_steelcraft.sawedoff_aq_sawedoff_blackgold.sawedoff_sp_nukestripe_brown.scar20_cu_scar20_intervention.sg553_sp_tape_dots_waves.tec9_hy_varicamo.usps_am_ddpat_purple.xm1014_cu_xm1014_caritas.xm1014_soch_mountains_limited_time`.split(`.`),
    authentic: [`ak47_cu_tribute_ak47`, `fiveseven_cu_fiveseven_urban_hazard`, `g3sg1_am_g3sg1_murky`, `glock_aq_glock_coiled`, `m4a1s_aq_m4a1s_basilisk`, `m4a4_cu_m4a4_griffin`, `mag7_sp_mag7_firebitten`, `mp9_cu_mp9_chevron`, `p2000_cu_p2000_fire_elemental`, `p250_aq_p250_cartel`, `sawedoff_aq_sawedoff_blackgold`, `scar20_cu_scar20_intervention`, `xm1014_cu_xm1014_caritas`]
  }, {
    id: `crate_community_6`,
    name: `Chroma Case`,
    set: `set_community_6`,
    decal: `chroma`,
    rare: ``,
    nameKey: `CSGO_set_community_6`,
    price: 250,
    icon: `crate_community_6`,
    mesh: `csgo`,
    items: `ak47_aq_ak47_cartel.aug_aug_cold_sentinel.awp_am_awp_glory.awp_hye_firework_patches.bizon_so_red.deagle_aq_deagle_naga.dualies_cu_elites_urbanstorm.dualies_cu_overpass_baby_dualies.fiveseven_fiveseven_desert_seal.galil_cu_galil_abrasion.galil_sp_mesh_slashes.glock_cu_glock_deathtoll.m249_cu_m249_sektor.m249_sp_mesh_python.m4a1s_hy_varicamo.m4a1s_sp_technowar_red.m4a4_cu_csgo_camo.m4a4_cu_m4a4_ancestral.m4a4_hy_red_hex.m4a4_hye_blue_m4a4.m4a4_m4a4_black_side_matte.mac10_am_mac10_malachite.mag7_so_greyblue.mp9_cu_mp9_deadly_poison.mp9_cu_mp9_latte.nova_nova_ocular.p250_cu_p250_mandala.p250_hy_forest_boreal.p90_so_stormfront.sawedoff_cu_sawedoff_deva.sawedoff_sp_palm_green.scar20_aq_scar20_leak.sg553_sp_zebracam_red.tec9_hye_batik_eyes_tec9.usps_am_intelligence_magenta.xm1014_aq_xm1014_sigla.xm1014_soe_yellow_xm`.split(`.`),
    authentic: [`ak47_aq_ak47_cartel`, `awp_am_awp_glory`, `deagle_aq_deagle_naga`, `dualies_cu_elites_urbanstorm`, `galil_cu_galil_abrasion`, `glock_cu_glock_deathtoll`, `m249_cu_m249_sektor`, `m4a4_cu_m4a4_ancestral`, `mac10_am_mac10_malachite`, `mp9_cu_mp9_deadly_poison`, `p250_cu_p250_mandala`, `sawedoff_cu_sawedoff_deva`, `scar20_aq_scar20_leak`, `xm1014_aq_xm1014_sigla`]
  }, {
    id: `crate_community_7`,
    name: `Chroma 2 Case`,
    set: `set_community_7`,
    decal: `chroma2`,
    rare: ``,
    nameKey: `CSGO_set_community_7`,
    price: 250,
    icon: `crate_community_7`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_mastery.aug_cu_anime_aug.awp_aq_awp_twine.bizon_cu_bizon-osiris.bizon_sp_leaves.cz75_cu_cz75_precision.deagle_am_bronze_sparkle.dualies_dual_elite_biblical_angel.famas_aq_famas_jinn.fiveseven_cu_fiveseven_banana.fiveseven_hy_ducts_green.galil_cu_galil_eco.galil_sp_phoenix_tags_purple.m249_sp_palm_night.m4a1s_cu_m4a1_hyper_beast.m4a4_m4a4_falak.m4a4_m4a4_zubastick_bw.m4a4_sp_nukestripe_orange.mac10_aa_fade.mac10_aa_fade_metallic.mac10_cu_mac10_neonrider.mag7_cu_mag7_redhot.mag7_so_sand.mp7_aq_mp7_ultramodern.mp9_gs_arctic_mp9.negev_am_negev_glory.nova_nova_smart.p250_aq_p250_contour.p250_hy_forest_night.p90_sp_bloom_orange.sawedoff_cu_sawedoff_origami.sawedoff_sp_snake.ssg08_aa_fade_grassland.tec9_so_ceramic.ump45_am_ump_racer.usps_am_lizard_red.xm1014_sp_nukestripe_maroon`.split(`.`),
    authentic: [`ak47_cu_ak47_mastery`, `awp_aq_awp_twine`, `cz75_cu_cz75_precision`, `deagle_am_bronze_sparkle`, `famas_aq_famas_jinn`, `fiveseven_cu_fiveseven_banana`, `galil_cu_galil_eco`, `m4a1s_cu_m4a1_hyper_beast`, `mac10_cu_mac10_neonrider`, `mag7_cu_mag7_redhot`, `mp7_aq_mp7_ultramodern`, `negev_am_negev_glory`, `p250_aq_p250_contour`, `sawedoff_cu_sawedoff_origami`, `ump45_am_ump_racer`]
  }, {
    id: `crate_community_8`,
    name: `Falchion Case`,
    set: `set_community_8`,
    decal: `bloodhound`,
    rare: `crate_community_8`,
    nameKey: `CSGO_set_community_8`,
    price: 250,
    icon: `crate_community_8`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_courage_alt.aug_hy_dry_wood.awp_cu_awp_hyper_beast.bizon_sp_nukestripe_brown.cz75_cu_cz75a_chastizer.dualies_dualies_mystic_conjunction_v3.famas_am_famas_dots.fiveseven_hy_forest_night.galil_cu_galilar_particles.galil_sp_spray_desert_sage.glock_aq_glock18_flames_blue.m249_sp_spray.m4a4_cu_m4a4_evil_daimyo.m4a4_m4a4_skrrrt_green.mac10_am_knots_brown.mac10_am_nuclear_skulls3_mac10.mac10_cu_overpass_squeak_mac10.mac10_hye_green_forest.mag7_so_stormfront.mp7_cu_mp7_nemsis.mp9_am_mp9_nitrogen.mp9_ht_blue_edges.negev_cu_negev_annihilator.nova_cu_nova_ranger.nova_so_green.p2000_aq_p2000_boom.p250_hy_gelpen.p90_cu_p90_mastery.p90_sp_dapple.sawedoff_sp_spray_desert_sage.sg553_cu_sg553_cyrex.ssg08_am_carbon_fiber.tec9_so_olive.ump45_cu_ump45_uproar.usps_cu_luggage_usp-s.usps_cu_usp_progressiv.xm1014_sp_tape_dots_urban`.split(`.`),
    authentic: [`ak47_cu_ak47_courage_alt`, `awp_cu_awp_hyper_beast`, `cz75_cu_cz75a_chastizer`, `famas_am_famas_dots`, `galil_cu_galilar_particles`, `glock_aq_glock18_flames_blue`, `m4a4_cu_m4a4_evil_daimyo`, `mp7_cu_mp7_nemsis`, `mp9_am_mp9_nitrogen`, `negev_cu_negev_annihilator`, `nova_cu_nova_ranger`, `p2000_aq_p2000_boom`, `p90_cu_p90_mastery`, `sg553_cu_sg553_cyrex`, `ump45_cu_ump45_uproar`, `usps_cu_usp_progressiv`]
  }, {
    id: `crate_community_9`,
    name: `Shadow Case`,
    set: `set_community_9`,
    decal: `shadow`,
    rare: `crate_community_9`,
    nameKey: `CSGO_set_community_9`,
    price: 250,
    icon: `crate_community_9`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_winter_sport.aug_hy_dune_trap.bizon_sp_tape_short_sand.cz75_am_royal.dualies_cu_dualberretta_dragons.dualies_gs_mother_of_pearl_elite.famas_cu_famas_lenta.fiveseven_hy_kimono_diamonds.g3sg1_gs_g3sg1_flux_purple.galil_gs_galil_nightwing.glock_aa_fade.glock_gs_glock18_wrathys.m249_gs_m249_nebula_crusader.m249_sp_zebracam.m4a1s_gs_m4a1s_snakebite_gold.m4a4_so_tornado.mac10_cu_mac10_alekhya_duo.mac10_mac10_arabesque_gold.mag7_cu_mag7_myrcene.mag7_gs_mag7_goold.mag7_hy_geometric_steps_green.mag7_so_yellow.mp7_cu_mp7_classified.mp9_hy_mtp.nova_so_red.p250_hy_hunter_modern.p250_hy_p250_crackshot.p90_sp_mesh_glacier.scar20_am_army_shine.scar20_gs_scar20_peacemaker03.ssg08_am_intelligence_orange.ssg08_cu_ssg08_technicality.tec9_so_teal.usps_cu_usp_kill_confirmed.usps_cu_usp_sandpapered.xm1014_aq_xm1014_scumbria.xm1014_sp_tire_tread_blue`.split(`.`),
    authentic: [`ak47_cu_ak47_winter_sport`, `dualies_cu_dualberretta_dragons`, `famas_cu_famas_lenta`, `g3sg1_gs_g3sg1_flux_purple`, `galil_gs_galil_nightwing`, `glock_gs_glock18_wrathys`, `m249_gs_m249_nebula_crusader`, `m4a1s_gs_m4a1s_snakebite_gold`, `mac10_cu_mac10_alekhya_duo`, `mag7_cu_mag7_myrcene`, `mp7_cu_mp7_classified`, `p250_hy_p250_crackshot`, `scar20_gs_scar20_peacemaker03`, `ssg08_cu_ssg08_technicality`, `usps_cu_usp_kill_confirmed`, `xm1014_aq_xm1014_scumbria`]
  }, {
    id: `crate_community_10`,
    name: `Revolver Case`,
    set: `set_community_10`,
    decal: `revolver`,
    rare: ``,
    nameKey: `CSGO_set_community_10`,
    price: 250,
    icon: `crate_community_10`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_point_disarray.aug_am_aug_jumble.aug_hy_flecktarn.bizon_cu_bizon_noxious.bizon_sp_tape_short_urban.deagle_aq_deagle_corinthian.dualies_hy_forest_night.fiveseven_cu_fiveseven_retrobution.fiveseven_hy_overpass_paintover_teal.g3sg1_cu_g3sg1_executioner.glock_aa_vertigo_blue.m4a1s_aa_fade_m4a1s.m4a4_gs_m4a4_royal_squire.m4a4_soo_polysoup_m4a4.mag7_mag7_circle_copper.mag7_soch_wildwood_mag7.mag7_sp_hazard_bravo.mp5sd_am_circuitboard_aqua.mp5sd_hye_gold_camo.mp9_hy_plaid2.negev_cu_negev_impact.nova_so_sand.p2000_am_p2000_imperial_red.p250_hy_kimono_diamonds_red.p90_cu_p90_shapewood.p90_sp_mesh_hot_and_cold.r8_aa_fade_revolver.r8_hy_webs.sawedoff_gs_sawedoff_necromancer.scar20_am_carbon_fiber.scar20_hy_scar20_jungler.sg553_gs_sg553_tiger_moth.ssg08_cu_ssg08_scorpion.tec9_cu_tec9_avalanche.tec9_so_tornado_bravo.usps_gs_usps_tactical_camo.xm1014_aq_xm1014_hot_rod.xm1014_xm1014_black_site`.split(`.`),
    authentic: [`ak47_cu_ak47_point_disarray`, `aug_am_aug_jumble`, `bizon_cu_bizon_noxious`, `deagle_aq_deagle_corinthian`, `fiveseven_cu_fiveseven_retrobution`, `g3sg1_cu_g3sg1_executioner`, `m4a4_gs_m4a4_royal_squire`, `negev_cu_negev_impact`, `p2000_am_p2000_imperial_red`, `p90_cu_p90_shapewood`, `r8_aa_fade_revolver`, `r8_hy_webs`, `sawedoff_gs_sawedoff_necromancer`, `scar20_hy_scar20_jungler`, `sg553_gs_sg553_tiger_moth`, `tec9_cu_tec9_avalanche`, `xm1014_aq_xm1014_hot_rod`]
  }, {
    id: `crate_community_11`,
    name: `Operation Wildfire Case`,
    set: `set_community_11`,
    decal: `wildfire`,
    rare: `crate_community_11`,
    nameKey: `CSGO_set_community_11`,
    price: 250,
    icon: `crate_community_11`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_supercharged.aug_hy_murano_blue.awp_cu_awp_mastery.bizon_cu_bizon_citizen.bizon_sp_wax_rub_bizon.deagle_aq_deserteagle_kumichodragon.dualies_aq_dualberettas_cartel.dualies_hy_gelpen_dark.famas_aq_famas_contour.fiveseven_cu_fiveseven_augmented.fiveseven_so_grey_nuclear_orange_five_seven.glock_am_aqua_flecks.glock_gs_glock18_award.m4a1s_aa_vertigo.m4a4_gs_m4a4_pioneer.m4a4_sp_bud_blue.mac10_am_mac10_electricity.mag7_gs_mag7_praetorian.mag7_sp_nukestripe_brown.mp5sd_mp5sd_chrome.mp7_an_navy.mp7_cu_mp7-commander.mp7_hy_varicamo_red.mp7_sp_mp7_impire.mp9_hy_splatter3.nova_cu_nova_hyperbeast.nova_soo_acrylic_flow_turquoise.p250_hy_nuclear_skulls4_p250.p90_sp_moro_textile_green_vine.scar20_am_zebra_dark.ssg08_cu_ssg08_necropos.ssg08_gs_ssg08_anubis.tec9_gs_tec9_jambiya.tec9_so_whiteout_tec9.usps_gs_usp_voltage.usps_gsch_bright_camo_usp.xm1014_xm1014_freight`.split(`.`),
    authentic: [`ak47_gs_ak47_supercharged`, `awp_cu_awp_mastery`, `bizon_cu_bizon_citizen`, `deagle_aq_deserteagle_kumichodragon`, `dualies_aq_dualberettas_cartel`, `famas_aq_famas_contour`, `fiveseven_cu_fiveseven_augmented`, `glock_gs_glock18_award`, `m4a4_gs_m4a4_pioneer`, `mac10_am_mac10_electricity`, `mag7_gs_mag7_praetorian`, `mp7_sp_mp7_impire`, `nova_cu_nova_hyperbeast`, `ssg08_cu_ssg08_necropos`, `tec9_gs_tec9_jambiya`, `usps_gs_usp_voltage`]
  }, {
    id: `crate_community_12`,
    name: `Chroma 3 Case`,
    set: `set_community_12`,
    decal: `chroma3`,
    rare: ``,
    nameKey: `CSGO_set_community_12`,
    price: 250,
    icon: `crate_community_12`,
    mesh: `csgo`,
    items: `aug_cu_aug_swallows.aug_gs_aug_aristocrat.aug_so_pmc.awp_gs_awp_phobos.bizon_gs_pp_bizon_harvester.cz75_am_army_shine.cz75_gs_cz75a_redastor.dualies_gs_dualberettas_ventilators.dualies_hy_numbers_green.fiveseven_cu_five_seven_daimyo.fiveseven_so_jungle.g3sg1_sp_g3sg1_militiaorange.galil_gs_galilar_incenerator.glock_am_emerald_marbleized_glock.glock_cu_glock_wasteland_rebel.m249_cu_m249_spectre.m4a1s_am_crystallized_dark_green.m4a1s_cu_m4a1s_soultaker.m4a1s_gs_m4a1_mecha_industries.m4a4_cu_m4a4_desolate_space.m4a4_spe_lightning.mac10_aq_mac_10_alien_camo.mag7_sp_palm_night.mp9_am_mp9_bioleak.mp9_mp9_dune_asp.nova_aq_nova_sci_fi.nova_soo_grass_photo_camo.p2000_gs_p2000_imperial_dragon.p2000_hy_p2000_oceani.p250_cu_p250_asiimov.p250_gs_p250_metal_panels.p250_hy_p250_tiger.p90_gs_p90_full_throttle.p90_sp_nukestripe_maroon.r8_cu_r8_cybersport.sawedoff_cu_sawed_off_lime.sawedoff_gs_sawedoff_fubar.scar20_an_emerald_bravo.scar20_gs_scar20_bloodsport.sg553_cu_sg553_aerial.sg553_cu_sg553_atlas.ssg08_gs_ssg08_armacore.ssg08_gs_ssg08_checker.tec9_am_tec9_redblast.tec9_am_tec_9_sea_salt.tec9_soch_tiger_stencil_tec9.ump45_cu_ump45_primalsaber.usps_ht_red_edges.xm1014_cu_xm1014_spectrum.zeus_cu_overpass_dragon_zeus`.split(`.`),
    authentic: `aug_cu_aug_swallows.aug_gs_aug_aristocrat.awp_gs_awp_phobos.bizon_gs_pp_bizon_harvester.cz75_gs_cz75a_redastor.dualies_gs_dualberettas_ventilators.fiveseven_cu_five_seven_daimyo.g3sg1_sp_g3sg1_militiaorange.galil_gs_galilar_incenerator.glock_cu_glock_wasteland_rebel.m249_cu_m249_spectre.m4a1s_cu_m4a1s_soultaker.m4a1s_gs_m4a1_mecha_industries.m4a4_cu_m4a4_desolate_space.mac10_aq_mac_10_alien_camo.mp9_am_mp9_bioleak.nova_aq_nova_sci_fi.p2000_gs_p2000_imperial_dragon.p2000_hy_p2000_oceani.p250_cu_p250_asiimov.p250_gs_p250_metal_panels.p90_gs_p90_full_throttle.r8_cu_r8_cybersport.sawedoff_cu_sawed_off_lime.sawedoff_gs_sawedoff_fubar.scar20_gs_scar20_bloodsport.sg553_cu_sg553_aerial.sg553_cu_sg553_atlas.ssg08_gs_ssg08_armacore.tec9_am_tec9_redblast.tec9_am_tec_9_sea_salt.ump45_cu_ump45_primalsaber.xm1014_cu_xm1014_spectrum`.split(`.`)
  }, {
    id: `crate_community_13`,
    name: `Gamma Case`,
    set: `set_community_13`,
    decal: `gamma`,
    rare: ``,
    nameKey: `CSGO_set_community_13`,
    price: 250,
    icon: `crate_community_13`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_anarchy.aug_gs_aug_aristocrat.aug_gs_aug_syd_mead.aug_so_space_marine.awp_gs_awp_phobos.bizon_gs_pp_bizon_harvester.cz75_am_carbon_fiber_cz75.cz75_gs_cz75_tread.deagle_aq_desert_eagle_constable.dualies_hy_vines.famas_gs_famas_rally.fiveseven_aq_five_seven_scumbria.fiveseven_cu_five_seven_daimyo.fiveseven_so_pmc.g3sg1_gs_g3sg1_ventilator.glock_am_gamma_doppler_phase1_glock.glock_cu_glock18_weasel.glock_cu_glock_wasteland_rebel.m4a1s_am_m4a1-s_alloy_orange.m4a1s_gs_m4a1_mecha_industries.m4a4_cu_m4a4_desolate_space.mac10_am_gold_brick.mac10_aq_mac_10_alien_camo.mag7_cu_mag7_tribal.mp5sd_gs_mp5_neon_flektarn.mp9_cu_mp9_narcis.mp9_mp9_urban_sovereign.negev_hy_negev_dazzle.nova_aq_nova_sci_fi.nova_sp_leaves.p2000_gs_p2000_imperial_dragon.p250_gs_p250_metal_panels.p250_hye_car_wrap_3.p90_cu_p90_grimm.p90_gs_p90_full_throttle.p90_sp_overpass_doodle_plum.r8_cu_r8_cybersport.sawedoff_cu_sawed_off_lime.scar20_aq_brass.scar20_gs_scar20_bloodsport.scar20_gs_scar20_powercore.sg553_cu_sg553_aerial.sg553_cu_sg556_triarch.ssg08_gsch_zeno_ssg08.tec9_am_tec_9_sea_salt.tec9_gs_tec9_supercharged.tec9_soe_snakeskin.ump45_cu_ump45_metritera.usps_hy_indigo_usp.xm1014_hy_xm1014_fractal_blue.zeus_hy_digicam_forest`.split(`.`),
    authentic: `ak47_cu_ak47_anarchy.aug_gs_aug_aristocrat.aug_gs_aug_syd_mead.awp_gs_awp_phobos.bizon_gs_pp_bizon_harvester.cz75_gs_cz75_tread.deagle_aq_desert_eagle_constable.famas_gs_famas_rally.fiveseven_aq_five_seven_scumbria.fiveseven_cu_five_seven_daimyo.g3sg1_gs_g3sg1_ventilator.glock_cu_glock18_weasel.glock_cu_glock_wasteland_rebel.m4a1s_gs_m4a1_mecha_industries.m4a4_cu_m4a4_desolate_space.mac10_aq_mac_10_alien_camo.mag7_cu_mag7_tribal.mp9_cu_mp9_narcis.negev_hy_negev_dazzle.nova_aq_nova_sci_fi.p2000_gs_p2000_imperial_dragon.p250_gs_p250_metal_panels.p90_cu_p90_grimm.p90_gs_p90_full_throttle.r8_cu_r8_cybersport.sawedoff_cu_sawed_off_lime.scar20_gs_scar20_bloodsport.scar20_gs_scar20_powercore.sg553_cu_sg553_aerial.sg553_cu_sg556_triarch.tec9_am_tec_9_sea_salt.tec9_gs_tec9_supercharged.ump45_cu_ump45_metritera.xm1014_hy_xm1014_fractal_blue`.split(`.`)
  }, {
    id: `crate_gamma_2`,
    name: `Gamma 2 Case`,
    set: `set_gamma_2`,
    decal: `gamma2`,
    rare: ``,
    nameKey: `CSGO_set_gamma_2`,
    price: 250,
    icon: `crate_gamma_2`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_anarchy.aug_gs_aug_syd_mead.aug_so_stormfront.cz75_am_czv2_mf.cz75_an_silver.cz75_gs_cz75_tread.deagle_aq_desert_eagle_constable.dualies_gs_dual_berettas_golden_venice.dualies_hy_zodiac1.famas_gs_famas_mecha.famas_gs_famas_rally.fiveseven_aq_five_seven_scumbria.fiveseven_so_red.g3sg1_gs_g3sg1_ventilator.g3sg1_gs_g3sg1_viper_yellow.glock_am_gamma_doppler_phase2_glock.glock_cu_glock18_weasel.m4a1s_am_m4a1s_bluesmoke.m4a1s_cu_m4a1_flashback.m4a4_gs_m4a4_sector.mac10_am_ren_red.mag7_am_mag7_malform.mag7_cu_mag7_tribal.mp5sd_ht_blur_camo_mp5sd.mp7_gs_final_pooldeadv2.mp9_cu_mp9_narcis.mp9_so_stormfront.negev_hy_negev_dazzle.nova_am_nova_sand.nova_sp_mesh_arctic_contrast.p250_hye_pink_coral.p90_cu_p90_grimm.p90_gs_p90_shallow_grave.p90_sp_spray_sand.sawedoff_cu_wp_sawedoff.scar20_cu_chevron_scar20.scar20_gs_scar20_powercore.sg553_cu_sg556_triarch.ssg08_cu_ssg08_dragonfire_scope.ssg08_ht_red_edges_fineline.tec9_gs_tec9_supercharged.tec9_soo_paint_splats_yellow.ump45_cu_ump45_metritera.usps_cu_usp_cyrex.usps_hy_varicamo_night.xm1014_hy_xm1014_fractal_blue.zeus_hye_earth_mandala_lc`.split(`.`),
    authentic: `ak47_cu_ak47_anarchy.aug_gs_aug_syd_mead.cz75_am_czv2_mf.cz75_gs_cz75_tread.deagle_aq_desert_eagle_constable.dualies_gs_dual_berettas_golden_venice.famas_gs_famas_mecha.famas_gs_famas_rally.fiveseven_aq_five_seven_scumbria.g3sg1_gs_g3sg1_ventilator.g3sg1_gs_g3sg1_viper_yellow.glock_cu_glock18_weasel.m4a1s_cu_m4a1_flashback.m4a4_gs_m4a4_sector.mag7_am_mag7_malform.mag7_cu_mag7_tribal.mp7_gs_final_pooldeadv2.mp9_cu_mp9_narcis.negev_hy_negev_dazzle.nova_am_nova_sand.p90_cu_p90_grimm.p90_gs_p90_shallow_grave.sawedoff_cu_wp_sawedoff.scar20_gs_scar20_powercore.sg553_cu_sg556_triarch.ssg08_cu_ssg08_dragonfire_scope.tec9_gs_tec9_supercharged.ump45_cu_ump45_metritera.usps_cu_usp_cyrex.xm1014_hy_xm1014_fractal_blue`.split(`.`)
  }, {
    id: `crate_community_15`,
    name: `Glove Case`,
    set: `set_community_15`,
    decal: `glove`,
    rare: `crate_community_15`,
    nameKey: `CSGO_set_community_15`,
    price: 250,
    icon: `crate_community_15`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_bloodsport.aug_sp_labyrinth3.awp_cu_awp_psychopath.bizon_hy_bizon_torn_green.cz75_am_czv2_mf.cz75_cu_c75a-tiger.cz75_gs_cz_snakes_purple.deagle_cu_desert_eagle_corroden.dualies_gs_dual_berettas_golden_venice.dualies_so_pmc.famas_gs_famas_mecha.fiveseven_cu_fiveseven_vein.fiveseven_soe_blue_and_chrome.g3sg1_gs_g3sg1_viper_yellow.galil_sp_galil_wave.glock_am_gamma_doppler_phase3_glock.m249_sp_m249_frog_original.m4a1s_am_metals.m4a1s_cu_m4a1_flashback.m4a1s_gs_m4a1_decimator.m4a4_gs_m4a4_sector.mac10_aa_mac10_the_last_dive.mac10_an_silver.mag7_am_mag7_malform.mp5sd_hy_bamboo_stmarc.mp7_gs_final_pooldeadv2.mp7_sp_mp7_tribal_yellow.mp9_so_yellow.nova_am_nova_sand.nova_sp_zebracam.p250_am_p250_sputnik.p250_p250_bullfrog.p90_gs_p90_shallow_grave.p90_sp_twigs.sawedoff_aq_sawedoff_zander2.sawedoff_cu_wp_sawedoff.scar20_cu_blueprint_scar.scar20_hy_authority_purple.ssg08_cu_ssg08_dragonfire_scope.ssg08_ht_swirl_ssg08.tec9_sp_leaf_orange.ump45_gs_ump_abyss.usps_cu_usp_cyrex.usps_cu_usps_noir.usps_so_khaki_green.xm1014_aq_xm_leaf_fade.zeus_soe_electric_blue`.split(`.`),
    authentic: `ak47_gs_ak47_bloodsport.awp_cu_awp_psychopath.bizon_hy_bizon_torn_green.cz75_am_czv2_mf.cz75_gs_cz_snakes_purple.deagle_cu_desert_eagle_corroden.dualies_gs_dual_berettas_golden_venice.famas_gs_famas_mecha.fiveseven_cu_fiveseven_vein.g3sg1_gs_g3sg1_viper_yellow.galil_sp_galil_wave.m249_sp_m249_frog_original.m4a1s_cu_m4a1_flashback.m4a1s_gs_m4a1_decimator.m4a4_gs_m4a4_sector.mac10_aa_mac10_the_last_dive.mag7_am_mag7_malform.mp7_gs_final_pooldeadv2.mp7_sp_mp7_tribal_yellow.nova_am_nova_sand.p250_am_p250_sputnik.p90_gs_p90_shallow_grave.sawedoff_aq_sawedoff_zander2.sawedoff_cu_wp_sawedoff.scar20_cu_blueprint_scar.ssg08_cu_ssg08_dragonfire_scope.ump45_gs_ump_abyss.usps_cu_usp_cyrex.usps_cu_usps_noir.xm1014_aq_xm_leaf_fade`.split(`.`)
  }, {
    id: `crate_community_16`,
    name: `Spectrum Case`,
    set: `set_community_16`,
    decal: `spectrum`,
    rare: ``,
    nameKey: `CSGO_set_community_16`,
    price: 250,
    icon: `crate_community_16`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_bloodsport.ak47_gs_ak_colony01_red.aug_sp_mesh_forest_fire.awp_cu_awp_hannya.awp_cu_awp_psychopath.bizon_hy_bizon_torn_green.cz75_cz75_hydraulics.cz75_gs_cz_snakes_purple.deagle_cu_desert_eagle_corroden.dualies_gs_dualberettas_cobra.dualies_so_space_marine.famas_sp_famas_macabre.fiveseven_cu_fiveseven_hyperbeast.fiveseven_cu_fiveseven_vein.fiveseven_soo_branches.galil_cu_galil_candychaos.galil_sp_galil_wave.glock_am_gamma_doppler_phase4_glock.m249_sp_m249_frog_original.m4a1s_an_red_m4a1s.m4a1s_cu_m4a1s_metritera.m4a1s_gs_m4a1_decimator.m4a4_cu_m4a4_hellfire.mac10_aa_mac10_the_last_dive.mac10_am_mac10_aloha.mac10_aq_oiled.mag7_am_mag7_caustic.mp5sd_hy_labrat_mp5.mp7_sp_mp7_tribal_yellow.mp9_soe_alpine_green.nova_train_shapes_01.p2000_cu_p2000_hunter.p250_am_p250_sputnik.p250_cu_p250_axiom.p250_p250_kintsugi.p90_hy_p90_barebones_blue.r8_aa_fade_metallic_revolver.sawedoff_aq_sawedoff_zander2.scar20_cu_blueprint_scar.scar20_hy_canals_tile.ssg08_cu_ssg08_deathshead.ssg08_hy_flowers_stmarc.tec9_aq_tec9_chalk_pattern.tec9_sp_mesh_army.ump45_aq_ump45_flameflower.ump45_gs_ump_abyss.usps_cu_usps_blueprint.usps_cu_usps_noir.usps_so_whiteout_riptide.xm1014_aq_xm_leaf_fade.zeus_zeus_standard_issue`.split(`.`),
    authentic: `ak47_gs_ak47_bloodsport.ak47_gs_ak_colony01_red.awp_cu_awp_hannya.awp_cu_awp_psychopath.bizon_hy_bizon_torn_green.cz75_gs_cz_snakes_purple.deagle_cu_desert_eagle_corroden.dualies_gs_dualberettas_cobra.famas_sp_famas_macabre.fiveseven_cu_fiveseven_hyperbeast.fiveseven_cu_fiveseven_vein.galil_cu_galil_candychaos.galil_sp_galil_wave.m249_sp_m249_frog_original.m4a1s_cu_m4a1s_metritera.m4a1s_gs_m4a1_decimator.m4a4_cu_m4a4_hellfire.mac10_aa_mac10_the_last_dive.mac10_am_mac10_aloha.mag7_am_mag7_caustic.mp7_sp_mp7_tribal_yellow.p2000_cu_p2000_hunter.p250_am_p250_sputnik.p250_cu_p250_axiom.p90_hy_p90_barebones_blue.sawedoff_aq_sawedoff_zander2.scar20_cu_blueprint_scar.ssg08_cu_ssg08_deathshead.tec9_aq_tec9_chalk_pattern.ump45_aq_ump45_flameflower.ump45_gs_ump_abyss.usps_cu_usps_blueprint.usps_cu_usps_noir.xm1014_aq_xm_leaf_fade`.split(`.`)
  }, {
    id: `crate_community_17`,
    name: `Operation Hydra Case`,
    set: `set_community_17`,
    decal: `hydra`,
    rare: ``,
    nameKey: `CSGO_set_community_17`,
    price: 250,
    icon: `crate_community_17`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_empress.ak47_gs_ak_colony01_red.aug_cu_aug_orange_triangle.aug_sp_mesh_safetyblack.awp_cu_awp_hannya.bizon_cu_bizon_all_in.cz75_gs_cz75_tacticat.cz75_gs_train_cz75.dualies_gs_dualberettas_cobra.dualies_so_tangerine.famas_sp_famas_macabre.fiveseven_cu_fiveseven_hyperbeast.fiveseven_sp_moro_textile_purple_yellow.g3sg1_gs_g3sg1_cetme_redux.galil_cu_galil_candychaos.glock_am_nuclear_skulls_green.glock_cu_glock_indigo.m4a1s_cu_m4a1-s_elegant.m4a1s_cu_m4a1s_metritera.m4a1s_gs_m4a1_shatter.m4a4_cu_m4a4_hellfire.mac10_am_mac10_aloha.mac10_am_mac10_oceani.mac10_cu_luggage_mac10.mag7_am_mag7_caustic.mp5sd_hy_trainarchitect.mp9_cu_mp9_goo.mp9_soe_ddpat_swirl_bw.p2000_aa_fade_metallic.p2000_cu_p2000_hunter.p250_cu_p250_axiom.p250_cu_p250_cybercroc.p250_p250_lotus_imprint_glitter_purple.p90_hy_p90_barebones_blue.r8_aa_flames.r8_gs_r8_llamacannon.scar20_hy_hunter_blaze_pink.scar20_hy_scar20_jungle_slipstream.sg553_gs_sg553_phantom.ssg08_cu_ssg08_deathshead.ssg08_hy_mayan_dreams_bravo.tec9_aq_tec9_chalk_pattern.tec9_cu_tec9_cracked_opal.tec9_sp_nukestripe_green_tec9.ump45_aq_ump45_flameflower.usps_cu_usps_blueprint.usps_soe_blue_and_gold.xm1014_aq_xm1014_ziggy_anarchy`.split(`.`),
    authentic: `ak47_gs_ak47_empress.ak47_gs_ak_colony01_red.aug_cu_aug_orange_triangle.awp_cu_awp_hannya.bizon_cu_bizon_all_in.cz75_gs_cz75_tacticat.dualies_gs_dualberettas_cobra.famas_sp_famas_macabre.fiveseven_cu_fiveseven_hyperbeast.g3sg1_gs_g3sg1_cetme_redux.galil_cu_galil_candychaos.glock_cu_glock_indigo.m4a1s_cu_m4a1s_metritera.m4a1s_gs_m4a1_shatter.m4a4_cu_m4a4_hellfire.mac10_am_mac10_aloha.mac10_am_mac10_oceani.mag7_am_mag7_caustic.mp9_cu_mp9_goo.p2000_cu_p2000_hunter.p250_cu_p250_axiom.p250_cu_p250_cybercroc.p90_hy_p90_barebones_blue.r8_gs_r8_llamacannon.scar20_hy_scar20_jungle_slipstream.sg553_gs_sg553_phantom.ssg08_cu_ssg08_deathshead.tec9_aq_tec9_chalk_pattern.tec9_cu_tec9_cracked_opal.ump45_aq_ump45_flameflower.usps_cu_usps_blueprint.xm1014_aq_xm1014_ziggy_anarchy`.split(`.`)
  }, {
    id: `crate_community_18`,
    name: `Spectrum 2 Case`,
    set: `set_community_18`,
    decal: `spectrum2`,
    rare: ``,
    nameKey: `CSGO_set_community_18`,
    price: 250,
    icon: `crate_community_18`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_empress.aug_cu_aug_orange_triangle.aug_sp_nukestripe_orange_aug.bizon_cu_bizon_all_in.cz75_cu_abstract_white_cz.cz75_gs_cz75_tacticat.cz75_hy_plaid2.dualies_soch_acrylic_grips.fiveseven_sp_tape_orange.g3sg1_gs_g3sg1_cetme_redux.glock_aq_brass.glock_cu_glock_indigo.m4a1s_cu_m4a1-s_silence.m4a1s_gs_m4a1_shatter.mac10_am_mac10_oceani.mac10_cu_mac10_propaganda.mp5sd_hy_varicamo_urban.mp7_so_whiteout.mp7_sp_bud_green.mp9_aa_hide-mp9.mp9_aa_pandora.mp9_cu_mp9_goo.mp9_soe_yellow_bits.p2000_aa_spacerace_orange.p250_cu_p250_cybercroc.p250_so_greyblue_p250.r8_am_phoenix_tags_blue.r8_gs_r8_llamacannon.scar20_hy_scar20_jungle_slipstream.scar20_hye_chrome_ripple.sg553_gs_sg553_phantom.ssg08_hy_ren_orange.tec9_cu_tec9_cracked_opal.tec9_tec9_perimeter_urban.usps_soe_purple.xm1014_aq_xm1014_ziggy_anarchy`.split(`.`),
    authentic: [`ak47_gs_ak47_empress`, `aug_cu_aug_orange_triangle`, `bizon_cu_bizon_all_in`, `cz75_gs_cz75_tacticat`, `g3sg1_gs_g3sg1_cetme_redux`, `glock_cu_glock_indigo`, `m4a1s_gs_m4a1_shatter`, `mac10_am_mac10_oceani`, `mp9_cu_mp9_goo`, `p250_cu_p250_cybercroc`, `r8_gs_r8_llamacannon`, `scar20_hy_scar20_jungle_slipstream`, `sg553_gs_sg553_phantom`, `tec9_cu_tec9_cracked_opal`, `xm1014_aq_xm1014_ziggy_anarchy`]
  }, {
    id: `crate_community_19`,
    name: `Clutch Case`,
    set: `set_community_19`,
    decal: `clutch`,
    rare: ``,
    nameKey: `CSGO_set_community_19`,
    price: 250,
    icon: `crate_community_19`,
    mesh: `csgo`,
    items: `ak47_cu_ak_neon_rider.aug_gs_aug_stymphalian_birds.aug_hy_aug_torn_orange.awp_aa_awp_fade.awp_am_awp_pawpaw.awp_gs_awp_death.bizon_cu_bizon_riot.cz75_cu_cz75_eco.cz75_hy_vertigoillusion.deagle_gs_deagle_aggressor.dualies_soch_marble_grips.dualies_sp_elites_winter_raider.famas_cu_famas_owl_orange.fiveseven_gs_fiveseven_hot_rod_violet.g3sg1_am_ancient_wine.g3sg1_gs_g3sg1_buccaneer.glock_aa_glock_18_urban_moon_fever.glock_aq_glock_dark-fall.glock_gs_glock_thunder_dust.m4a1s_cu_m4a1_snake.m4a1s_cu_m4a1s_nightmare.m4a4_cu_m4a4_neo_noir.mac10_cu_mac10_scarab.mag7_aq_mag7_swag7.mp5sd_hye_mp5_car_wrap4.mp7_gs_mp7_bloodsport.mp7_gs_powercore_mp7.mp9_cu_mp9_black_sand.mp9_cu_mp9_vein.mp9_sp_moro_carving_yellow.negev_sp_negev_lionfish.nova_cu_nova_toy_soldier.nova_gs_nova_anchorite.p2000_am_black_panther.p2000_cu_p2000_urban_hazard.p250_so_sand.p90_gs_p90_tread.r8_aq_titanium_acid.r8_cu_r8_survivalist.r8_gs_revolver_tread.sawedoff_cu_sawedoff_devourer.scar20_scar_arctic_camo_panels.sg553_sp_sg533_aloha.ssg08_hy_ssg08_marker.tec9_cu_tec9_snake.tec9_tec9_sultan.ump45_cu_ump45_white_fang.usps_cu_usp_cut.usps_soe_tropical.xm1014_cu_xm1014_oxide_blaze`.split(`.`),
    authentic: `ak47_cu_ak_neon_rider.aug_gs_aug_stymphalian_birds.aug_hy_aug_torn_orange.awp_am_awp_pawpaw.awp_gs_awp_death.bizon_cu_bizon_riot.cz75_cu_cz75_eco.deagle_gs_deagle_aggressor.dualies_sp_elites_winter_raider.famas_cu_famas_owl_orange.fiveseven_gs_fiveseven_hot_rod_violet.g3sg1_gs_g3sg1_buccaneer.glock_aa_glock_18_urban_moon_fever.glock_gs_glock_thunder_dust.m4a1s_cu_m4a1s_nightmare.m4a4_cu_m4a4_neo_noir.mag7_aq_mag7_swag7.mp7_gs_mp7_bloodsport.mp7_gs_powercore_mp7.mp9_cu_mp9_black_sand.mp9_cu_mp9_vein.negev_sp_negev_lionfish.nova_cu_nova_toy_soldier.nova_gs_nova_anchorite.p2000_cu_p2000_urban_hazard.p90_gs_p90_tread.r8_cu_r8_survivalist.r8_gs_revolver_tread.sawedoff_cu_sawedoff_devourer.sg553_sp_sg533_aloha.tec9_cu_tec9_snake.ump45_cu_ump45_white_fang.usps_cu_usp_cut.xm1014_cu_xm1014_oxide_blaze`.split(`.`)
  }, {
    id: `crate_community_20`,
    name: `Horizon Case`,
    set: `set_community_20`,
    decal: `horizon`,
    rare: ``,
    nameKey: `CSGO_set_community_20`,
    price: 250,
    icon: `crate_community_20`,
    mesh: `csgo`,
    items: `ak47_cu_ak_neon_rider.aug_hy_aug_torn_orange.awp_am_awp_pawpaw.awp_awp_longdog.cz75_cu_cz75_eco.cz75_hye_paisley_desat.deagle_gs_deagle_aggressor.dualies_soe_acrylic_flow3.dualies_sp_elites_winter_raider.famas_cu_famas_owl_orange.g3sg1_cu_chronos_g3sg1.g3sg1_gs_g3sg1_buccaneer.glock_aq_oiled.glock_gs_glock_thunder_dust.m4a1s_cu_m4a1s_nightmare.m4a1s_cue_stratosphere.mac10_gs_mac10_checker.mp5sd_so_orange_accents3.mp7_gs_powercore_mp7.mp9_am_metal_inlay.mp9_am_mirage_flowers_metalic.mp9_an_red.mp9_cu_mp9_vein.mp9_sp_tape_dots_bravo.nova_cu_nova_toy_soldier.p2000_am_chainmail.p250_so_whiteout.p90_gs_p90_tread.r8_cu_r8_survivalist.r8_gs_revolver_acanthus_bronze.sawedoff_cu_sawedoff_devourer.scar20_scar_refraction_v4.ssg08_hy_trainarchitect_green.tec9_cu_tec9_snake.ump45_aa_engine_performance.usps_sp_ancient_bright`.split(`.`),
    authentic: [`ak47_cu_ak_neon_rider`, `aug_hy_aug_torn_orange`, `awp_am_awp_pawpaw`, `cz75_cu_cz75_eco`, `deagle_gs_deagle_aggressor`, `dualies_sp_elites_winter_raider`, `famas_cu_famas_owl_orange`, `g3sg1_gs_g3sg1_buccaneer`, `glock_gs_glock_thunder_dust`, `m4a1s_cu_m4a1s_nightmare`, `mp7_gs_powercore_mp7`, `mp9_cu_mp9_vein`, `nova_cu_nova_toy_soldier`, `p90_gs_p90_tread`, `r8_cu_r8_survivalist`, `sawedoff_cu_sawedoff_devourer`, `tec9_cu_tec9_snake`]
  }, {
    id: `crate_community_21`,
    name: `Danger Zone Case`,
    set: `set_community_21`,
    decal: `dangerzone`,
    rare: ``,
    nameKey: `CSGO_set_community_21`,
    price: 250,
    icon: `crate_community_21`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_asiimov.ak47_cu_ak47_aztec.aug_cu_aug_momentum.awp_awp_queens_gambit.awp_cu_awp_neonoir.awp_cu_awp_viper.cz75_so_indigo_and_grey.deagle_gs_deagle_exo.deagle_gs_deagle_mecha.dualies_soo_rose_gold.famas_sp_famas_ghost_insects.fiveseven_cu_five_seven_angry.g3sg1_gs_g3sg1_savage.g3sg1_hy_arctic.galil_hy_galil_signal_red.galil_sp_galil_akoben.glock_cu_glock-liquescent.glock_cu_glock18_corroden.m4a1s_gs_m4a1_vertigo.m4a4_gs_m4a4_chopper_ghost.m4a4_gs_m4a4_emperor.mac10_gs_mac10_exo_pipes.mac10_gs_mac10_fish_bait.mac10_gs_mac10_snake.mp5sd_gs_mp5_festival_drip.mp5sd_gs_mp5sd_astromatic.mp5sd_soe_red.mp7_cu_mp7_racketeer.mp9_gs_mp9_colony01.mp9_sp_tape_orange.nova_gs_nova_hunter_brute.p2000_am_numbers_red_blue.p250_aa_p250_gravediggers.p250_aq_p250_verdigris.p250_soch_hunter_blaze_p250.p90_cu_p90_offworld.r8_cu_revolver_oppressor.r8_hy_brush_camo_tan.sawedoff_cu_sawedoff_black_sand.scar20_scar_sirocco.sg553_gs_sg553_over_heated.ssg08_hye_comic_shapes.tec9_cu_tec9_bamboo.tec9_gs_tec9_fubar.ump45_aa_fade_mp7.ump45_aa_ump45_moonrise_sunset.ump45_cu_ump_arrows.usps_cu_usp_flashback.usps_sp_labyrinth2.xm1014_cu_xm1014_incinerator`.split(`.`),
    authentic: `ak47_cu_ak47_asiimov.ak47_cu_ak47_aztec.aug_cu_aug_momentum.awp_cu_awp_neonoir.awp_cu_awp_viper.deagle_gs_deagle_exo.deagle_gs_deagle_mecha.famas_sp_famas_ghost_insects.fiveseven_cu_five_seven_angry.g3sg1_gs_g3sg1_savage.galil_hy_galil_signal_red.galil_sp_galil_akoben.glock_cu_glock18_corroden.m4a4_gs_m4a4_chopper_ghost.m4a4_gs_m4a4_emperor.mac10_gs_mac10_exo_pipes.mac10_gs_mac10_fish_bait.mp5sd_gs_mp5_festival_drip.mp5sd_gs_mp5sd_astromatic.mp7_cu_mp7_racketeer.mp9_gs_mp9_colony01.nova_gs_nova_hunter_brute.p250_aa_p250_gravediggers.p250_aq_p250_verdigris.p90_cu_p90_offworld.r8_cu_revolver_oppressor.sawedoff_cu_sawedoff_black_sand.sg553_gs_sg553_over_heated.tec9_cu_tec9_bamboo.tec9_gs_tec9_fubar.ump45_aa_ump45_moonrise_sunset.ump45_cu_ump_arrows.usps_cu_usp_flashback.xm1014_cu_xm1014_incinerator`.split(`.`)
  }, {
    id: `crate_community_22`,
    name: `Prisma Case`,
    set: `set_community_22`,
    decal: `community_22`,
    rare: ``,
    nameKey: `CSGO_set_community_22`,
    price: 250,
    icon: `crate_community_22`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_aztec.ak47_gs_ak47_nibbler.aug_cu_aug_momentum.aug_cu_aug_whitefang.awp_awp_sovereign_flame.awp_cu_awp_viper.awp_cu_awp_virus.bizon_cu_bizon_road_warrior.cz75_soe_pink_pearl.deagle_gs_deagle_exo.dualies_gs_dual_elites_rose.dualies_sp_dry_wood.famas_sp_famas_ghost_insects.fiveseven_cu_five_seven_angry.g3sg1_cu_g3sg1_blacksand.g3sg1_hy_arctic_contrast.galil_sp_galil_akoben.glock_cu_glock_ramzes.m249_gs_m249_warbird_veteran.m4a1s_gs_m4a1s_milspec.m4a4_gs_m4a4_emperor.mac10_gs_mac10_fish_bait.mac10_gs_mac10_stalker.mac10_hy_ddpat_urb.mp5sd_gs_mp5_etch.mp5sd_gs_mp5sd_astromatic.mp5sd_sp_lime_hex.mp7_cu_mp7_racketeer.mp7_cu_mp7_replica.mp9_sp_tape_short_sand.nova_cu_nova_featherswing.p2000_am_scorpion_p2000.p2000_cu_p2000_obsidian.p250_aq_p250_verdigris.p250_soe_yellow_swirl.p90_cu_p90_offworld.r8_cu_revolver_oppressor.r8_gs_r8_memento.r8_r8_monarch_extended.scar20_so_mustard_scar20.scar20_sp_scar20_striker_dust.sg553_cu_sg553_reactor.ssg08_cu_ssg08_tickler.ssg08_hye_tiger2.tec9_cu_tec9_bamboo.tec9_gs_tec9_decimator.ump45_aa_fade_ump.ump45_aa_ump45_moonrise_sunset.usps_sp_leaves.xm1014_cu_xm1014_incinerator`.split(`.`),
    authentic: `ak47_cu_ak47_aztec.ak47_gs_ak47_nibbler.aug_cu_aug_momentum.aug_cu_aug_whitefang.awp_cu_awp_viper.awp_cu_awp_virus.bizon_cu_bizon_road_warrior.deagle_gs_deagle_exo.dualies_gs_dual_elites_rose.famas_sp_famas_ghost_insects.fiveseven_cu_five_seven_angry.g3sg1_cu_g3sg1_blacksand.galil_sp_galil_akoben.m249_gs_m249_warbird_veteran.m4a4_gs_m4a4_emperor.mac10_gs_mac10_fish_bait.mac10_gs_mac10_stalker.mp5sd_gs_mp5_etch.mp5sd_gs_mp5sd_astromatic.mp7_cu_mp7_racketeer.mp7_cu_mp7_replica.nova_cu_nova_featherswing.p2000_cu_p2000_obsidian.p250_aq_p250_verdigris.p90_cu_p90_offworld.r8_cu_revolver_oppressor.r8_gs_r8_memento.scar20_sp_scar20_striker_dust.sg553_cu_sg553_reactor.ssg08_cu_ssg08_tickler.tec9_cu_tec9_bamboo.tec9_gs_tec9_decimator.ump45_aa_ump45_moonrise_sunset.xm1014_cu_xm1014_incinerator`.split(`.`)
  }, {
    id: `crate_community_23`,
    name: `Shattered Web Case`,
    set: `set_community_23`,
    decal: `community_23`,
    rare: ``,
    nameKey: `CSGO_set_community_23`,
    price: 250,
    icon: `crate_community_23`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_nibbler.aug_am_aug_death_by_doggy.aug_cu_aug_whitefang.awp_cu_awp_virus.awp_cu_awp_wildfire.awp_cu_medieval_dragon_awp.bizon_cu_bizon_road_warrior.cz75_sp_palm_night.dualies_gs_dual_elites_classic.dualies_gs_dual_elites_rose.dualies_sp_engine_dirty.famas_cu_famas_nuke_tension.famas_gs_famas_legacy_gold.fiveseven_cu_fiveseven_gsg9.g3sg1_cu_g3sg1_blacksand.g3sg1_hy_desert.glock_cu_glock_hero.glock_cu_money_glock.m249_aq_m249_aztec.m249_gs_m249_warbird_veteran.m4a1s_gs_m4a1s_operator.mac10_gs_mac10_dust_crate.mac10_gs_mac10_stalker.mac10_hy_vertigospray_blue.mag7_gs_mag7_popdog.mp5sd_gs_mp5_etch.mp5sd_gs_mp5_fbi.mp5sd_sp_overpass_paint_pen_neon.mp7_cu_mp7_replica.mp9_cu_mp9_hydra.negev_am_army_shine.nova_cu_nova_featherswing.p2000_an_silver.p2000_cu_p2000_obsidian.p250_gs_p250_inferno.p250_sp_desert_skulls_dawn.p90_cu_p90_nostalgia.r8_gs_r8_memento.r8_so_night.scar20_cu_scar_assault.scar20_so_pmc.scar20_sp_scar20_striker_dust.sg553_cu_sg553_reactor.ssg08_cu_ssg08_tickler.ssg08_so_ceramic_green_ssg08.tec9_cu_tec9_flash.tec9_gs_tec9_decimator.ump45_aa_flames.ump45_cu_ump_bomb.usps_sp_mesh_safetyred`.split(`.`),
    authentic: `ak47_gs_ak47_nibbler.aug_am_aug_death_by_doggy.aug_cu_aug_whitefang.awp_cu_awp_virus.awp_cu_awp_wildfire.bizon_cu_bizon_road_warrior.dualies_gs_dual_elites_classic.dualies_gs_dual_elites_rose.famas_cu_famas_nuke_tension.famas_gs_famas_legacy_gold.fiveseven_cu_fiveseven_gsg9.g3sg1_cu_g3sg1_blacksand.glock_cu_glock_hero.m249_aq_m249_aztec.m249_gs_m249_warbird_veteran.mac10_gs_mac10_dust_crate.mac10_gs_mac10_stalker.mag7_gs_mag7_popdog.mp5sd_gs_mp5_etch.mp5sd_gs_mp5_fbi.mp7_cu_mp7_replica.mp9_cu_mp9_hydra.nova_cu_nova_featherswing.p2000_cu_p2000_obsidian.p250_gs_p250_inferno.p90_cu_p90_nostalgia.r8_gs_r8_memento.scar20_cu_scar_assault.scar20_sp_scar20_striker_dust.sg553_cu_sg553_reactor.ssg08_cu_ssg08_tickler.tec9_cu_tec9_flash.tec9_gs_tec9_decimator.ump45_cu_ump_bomb`.split(`.`)
  }, {
    id: `crate_community_24`,
    name: `Anniversary Case`,
    set: `set_community_24`,
    decal: `community_24`,
    rare: `crate_community_24`,
    nameKey: `CSGO_set_community_24`,
    price: 250,
    icon: `crate_community_24`,
    mesh: `csgo`,
    items: `aug_am_aug_death_by_doggy.awp_cu_awp_wildfire.awp_cu_medusa_awp.cz75_sp_tape_short_jungle.dualies_gs_dual_elites_classic.famas_aa_wiring_yellow.famas_cu_famas_nuke_tension.famas_gs_famas_legacy_gold.fiveseven_cu_fiveseven_gsg9.g3sg1_hy_kimono_diamonds_orange.glock_cu_glock_hero.glock_glock_ghost_protocol_red.m249_aq_m249_aztec.m4a1s_ht_abstract_wind.mac10_gs_mac10_dust_crate.mac10_hye_car_wrap4.mag7_gs_mag7_popdog.mp5sd_gs_mp5_fbi.mp5sd_sp_tape_short_rally.mp9_cu_mp9_hydra.mp9_hy_nuclear_pattern2_mp9.mp9_hye_blue_paisley.mp9_hye_pink_tiger.negev_cu_overpass_graf_negev.p2000_cu_luggage_p2000.p250_gs_p250_inferno.p250_sp_kimono_diamonds.p90_cu_p90_nostalgia.r8_so_orange_accents.scar20_cu_scar_assault.scar20_so_stormfront.ssg08_so_moss.tec9_cu_tec9_flash.ump45_am_carbon_fiber.ump45_cu_ump_bomb.usps_usps_silent_boy`.split(`.`),
    authentic: [`aug_am_aug_death_by_doggy`, `awp_cu_awp_wildfire`, `dualies_gs_dual_elites_classic`, `famas_cu_famas_nuke_tension`, `famas_gs_famas_legacy_gold`, `fiveseven_cu_fiveseven_gsg9`, `glock_cu_glock_hero`, `m249_aq_m249_aztec`, `mac10_gs_mac10_dust_crate`, `mag7_gs_mag7_popdog`, `mp5sd_gs_mp5_fbi`, `mp9_cu_mp9_hydra`, `p250_gs_p250_inferno`, `p90_cu_p90_nostalgia`, `scar20_cu_scar_assault`, `tec9_cu_tec9_flash`, `ump45_cu_ump_bomb`]
  }, {
    id: `crate_community_25`,
    name: `Prisma 2 Case`,
    set: `set_community_25`,
    decal: `community_25`,
    rare: ``,
    nameKey: `CSGO_set_community_25`,
    price: 250,
    icon: `crate_community_25`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_anubis.aug_gs_aug_thunderstorm.awp_cu_awp_vein.awp_cu_overpass_crakow_awp.bizon_gs_bizon_hellraider.cz75_cu_cz75_cerakote.deagle_aa_flames.deagle_cu_deag_printstream.deagle_cu_deagle_replica.famas_am_carbon_fiber.g3sg1_hy_varicamo.galil_gs_galil_phoenix.glock_cu_glock18_warmaiden.glock_cu_glock_eyecontact.glock_glock_ifrit_lattice.m4a1s_cu_m4a1s_csgo2048.m4a1s_hy_forest_boreal.m4a4_cu_m4a4_queenfairy.mac10_cu_mac10_isoonna.mac10_cu_mac10_nacre.mac10_hye_green_camo.mag7_cu_mag7_monster_call.mag7_gs_mag7_justice.mp5sd_cu_mp5_desert_strike.mp5sd_gs_mp5sd_wasteland_legacy.mp7_aa_fade_mp7.negev_cu_negev_prototype.negev_cu_negev_ultralight.negev_gs_negev_thor.p2000_aq_p2000_acid_clover.p2000_aq_p2000_lost_world.p2000_gs_p2000-sport.p250_cu_p250_cassette.p250_sp_lace.p90_gs_p90_container.r8_gs_r8_leviathan.r8_so_orange_accents3.sawedoff_cu_sawedoff_apocalypto.scar20_gs_scar20_enforcer.scar20_sp_mesh_sand.sg553_cu_sg553_darkwing.sg553_gs_sg553_rusty.ssg08_cu_ssg08_fever_dream.ssg08_cu_ssg08_mainframe.ssg08_so_rune_stone.tec9_gs_tec9_guerilla.ump45_am_circuitboard_green.usps_usps_spiral_glitch_iridescent.xm1014_cu_xm1014_amulet_blue`.split(`.`),
    authentic: `ak47_cu_ak47_anubis.aug_gs_aug_thunderstorm.awp_cu_awp_vein.bizon_gs_bizon_hellraider.cz75_cu_cz75_cerakote.deagle_cu_deag_printstream.deagle_cu_deagle_replica.galil_gs_galil_phoenix.glock_cu_glock18_warmaiden.glock_cu_glock_eyecontact.m4a1s_cu_m4a1s_csgo2048.m4a4_cu_m4a4_queenfairy.mac10_cu_mac10_isoonna.mac10_cu_mac10_nacre.mag7_cu_mag7_monster_call.mag7_gs_mag7_justice.mp5sd_cu_mp5_desert_strike.mp5sd_gs_mp5sd_wasteland_legacy.negev_cu_negev_prototype.negev_cu_negev_ultralight.p2000_aq_p2000_acid_clover.p2000_aq_p2000_lost_world.p250_cu_p250_cassette.p90_gs_p90_container.r8_gs_r8_leviathan.sawedoff_cu_sawedoff_apocalypto.scar20_gs_scar20_enforcer.sg553_cu_sg553_darkwing.sg553_gs_sg553_rusty.ssg08_cu_ssg08_fever_dream.ssg08_cu_ssg08_mainframe.tec9_gs_tec9_guerilla.xm1014_cu_xm1014_amulet_blue`.split(`.`)
  }, {
    id: `crate_community_26`,
    name: `Fracture Case`,
    set: `set_community_26`,
    decal: `community_26`,
    rare: ``,
    nameKey: `CSGO_set_community_26`,
    price: 250,
    icon: `crate_community_26`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_anubis.awp_cue_jump_line.awp_gs_awp_exoskeleton.bizon_gs_bizon_hellraider.cz75_gs_cz75_vendetta.deagle_am_circuitboard_orange.deagle_cu_deag_printstream.dualies_gs_dual_elites_dezastre.famas_am_nuclear_pattern4_famas.fiveseven_cu_five_seven_diary.g3sg1_gs_g3sg1_disrupt.g3sg1_so_green.galil_gs_galil_phoenix.galil_gs_galil_vandal.glock_cu_glock_eyecontact.glock_cu_glock_noir.glock_glock_jdpeek.m249_cu_m249_deep_relief.m4a1s_cu_m4a1s_printstream.m4a1s_hy_icarus.m4a4_cu_m4a4_cyberpunk.m4a4_cu_m4a4_queenfairy.mac10_cu_mac10_isoonna.mac10_mac10_kamicatze.mag7_cu_mag7_monster_call.mp5sd_gs_mp5_conditionzero.mp5sd_gs_mp5sd_wasteland_legacy.mp7_am_circuitboard_green.negev_cu_negev_ultralight.negev_hy_arctic_contrast.nova_cu_nova_polymer.p2000_aq_p2000_lost_world.p2000_ht_facet_p2000.p250_cu_p250_cassette.p250_cu_p250_infect.p250_sp_nukestripe_green.p90_gs_p90_container.p90_hy_p90_dino_rampage.r8_soch_copper_accent_revolver.scar20_sp_palm.sg553_gs_sg553_rusty.ssg08_cu_ssg08_chromatic.ssg08_cu_ssg08_mainframe.ssg08_so_sand.tec9_gs_tec9_guerilla.ump45_cu_labyrinth.ump45_gs_ump_gold_bismuth.usps_cu_usp_krokos.xm1014_am_ancient_warm.xm1014_cu_xm1014_amulet_blue`.split(`.`),
    authentic: `ak47_cu_ak47_anubis.awp_gs_awp_exoskeleton.bizon_gs_bizon_hellraider.cz75_gs_cz75_vendetta.deagle_cu_deag_printstream.dualies_gs_dual_elites_dezastre.fiveseven_cu_five_seven_diary.g3sg1_gs_g3sg1_disrupt.galil_gs_galil_phoenix.galil_gs_galil_vandal.glock_cu_glock_eyecontact.glock_cu_glock_noir.m249_cu_m249_deep_relief.m4a1s_cu_m4a1s_printstream.m4a4_cu_m4a4_cyberpunk.m4a4_cu_m4a4_queenfairy.mac10_cu_mac10_isoonna.mag7_cu_mag7_monster_call.mp5sd_gs_mp5_conditionzero.mp5sd_gs_mp5sd_wasteland_legacy.negev_cu_negev_ultralight.nova_cu_nova_polymer.p2000_aq_p2000_lost_world.p250_cu_p250_cassette.p250_cu_p250_infect.p90_gs_p90_container.p90_hy_p90_dino_rampage.sg553_gs_sg553_rusty.ssg08_cu_ssg08_chromatic.ssg08_cu_ssg08_mainframe.tec9_gs_tec9_guerilla.ump45_gs_ump_gold_bismuth.usps_cu_usp_krokos.xm1014_cu_xm1014_amulet_blue`.split(`.`)
  }, {
    id: `crate_community_27`,
    name: `Operation Broken Fang Case`,
    set: `set_community_27`,
    decal: `community_27`,
    rare: ``,
    nameKey: `CSGO_set_community_27`,
    price: 250,
    icon: `crate_community_27`,
    mesh: `csgo`,
    items: `awp_gs_awp_enamel.awp_gs_awp_exoskeleton.cz75_gs_cz75_vendetta.deagle_am_jorm_green.dualies_gs_dual_elites_dezastre.famas_am_nuclear_skulls2_famas.fiveseven_cu_five_seven_diary.g3sg1_gs_g3sg1_disrupt.g3sg1_so_pmc.galil_gs_galil_vandal.glock_cu_glock_noir.glock_glock_mirror_maze_v2_pearl.m249_cu_m249_deep_relief.m4a1s_cu_m4a1s_printstream.m4a1s_hy_overpass_doodle_m4a1s.m4a4_cu_m4a4_cyberpunk.mac10_mac10_train_crash.mp5sd_gs_mp5_conditionzero.mp7_am_heist_plans_yellow.mp9_mp9_prototype_extended.mp9_mp9_vinyl.negev_an_navy.negev_hy_ducts_yellow.nova_cu_nova_polymer.p2000_hy_granite.p250_cu_p250_infect.p250_sp_tape.p90_hy_p90_dino_rampage.r8_soch_indigo_grips.sg553_aa_desert_bloom_bright.ssg08_cu_ssg08_chromatic.ssg08_soch_blorb_bw.ump45_cu_ump45_x-ray_machine.ump45_gs_ump_gold_bismuth.usps_cu_usp_krokos.xm1014_am_authority_brown`.split(`.`),
    authentic: [`awp_gs_awp_exoskeleton`, `cz75_gs_cz75_vendetta`, `dualies_gs_dual_elites_dezastre`, `fiveseven_cu_five_seven_diary`, `g3sg1_gs_g3sg1_disrupt`, `galil_gs_galil_vandal`, `glock_cu_glock_noir`, `m249_cu_m249_deep_relief`, `m4a1s_cu_m4a1s_printstream`, `m4a4_cu_m4a4_cyberpunk`, `mp5sd_gs_mp5_conditionzero`, `nova_cu_nova_polymer`, `p250_cu_p250_infect`, `p90_hy_p90_dino_rampage`, `ssg08_cu_ssg08_chromatic`, `ump45_gs_ump_gold_bismuth`, `usps_cu_usp_krokos`]
  }, {
    id: `crate_community_28`,
    name: `Snakebite Case`,
    set: `set_community_28`,
    decal: `community_28`,
    rare: ``,
    nameKey: `CSGO_set_community_28`,
    price: 250,
    icon: `crate_community_28`,
    mesh: `csgo`,
    items: `ak47_gs_ak47_professional.awp_gs_awp_gungnir.cz75_cu_cz75_whirlwind.deagle_am_numbers_bronze.deagle_cu_deag_trigger_discipline.famas_am_numbers_magenta.g3sg1_soo_g3sg1_tomato.galil_cu_galil_chroma_pink.glock_gs_glock_polymer.glock_gsch_axia_glock.m249_gs_m249_combine.m4a1s_hye_animal_print_90s.m4a4_cu_m4a4_love.mac10_cu_mac10_portable.mac10_mac10_video_cam.mp7_gs_constellation_dark_mp7.mp9_cu_mp9_food_chain.negev_cu_negev_devtexture.negev_hy_phoenix_tags_red.negev_hy_varicamo_desert.negev_hy_vertigospray.nova_cu_overpass_wurst_nova.nova_sp_nova_wind_dispersal.p2000_hy_mottled_sand.p250_gs_p250_cybershell.p90_aa_ancient_brown.r8_gs_r8_rustking.r8_soch_smoke_grips.sg553_aa_ruins_green.sg553_gs_sg553_deathmetal.ssg08_soo_acrylic_flow_pink.ump45_am_ump45_electrowave.ump45_cu_ump_crime_scene.usps_gs_usps_hangedman.xm1014_am_knots_silver.xm1014_aq_xm1014_punk`.split(`.`),
    authentic: [`ak47_gs_ak47_professional`, `cz75_cu_cz75_whirlwind`, `deagle_cu_deag_trigger_discipline`, `galil_cu_galil_chroma_pink`, `glock_gs_glock_polymer`, `m249_gs_m249_combine`, `m4a4_cu_m4a4_love`, `mac10_cu_mac10_portable`, `mp9_cu_mp9_food_chain`, `negev_cu_negev_devtexture`, `nova_sp_nova_wind_dispersal`, `p250_gs_p250_cybershell`, `r8_gs_r8_rustking`, `sg553_gs_sg553_deathmetal`, `ump45_am_ump45_electrowave`, `usps_gs_usps_hangedman`, `xm1014_aq_xm1014_punk`]
  }, {
    id: `crate_community_29`,
    name: `Operation Riptide Case`,
    set: `set_community_29`,
    decal: `community_29`,
    rare: ``,
    nameKey: `CSGO_set_community_29`,
    price: 250,
    icon: `crate_community_29`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_nightwish.ak47_gs_ak47_abstract.aug_gs_aug_plague.awp_gs_awp_hydra.bizon_cu_bizon_spacecat.bizon_gs_bizon_flasher.deagle_am_seastorm.deagle_cu_deagle_kitch.dualies_cu_elites_beware.dualies_gs_dual_berettas_tread.famas_am_zebra_dark.famas_cu_famas_spectron.famas_gs_famas_rapid_eyes.fiveseven_cu_fiveseven_alpha_omega.fiveseven_gs_five_seven_efusion.g3sg1_cu_g3sg1_glade.g3sg1_cu_g3sg1_tacticalmap.g3sg1_sp_khaki_camo.glock_cu_glock_snackattack.glock_ht_white_edges.m4a1s_gs_m4a1s_insomnia.m4a1s_hye_spyglitch_green_m4a1s.m4a4_gs_m4_flowers.mac10_cu_mac10_pixie.mac10_cu_mac10_toybox.mac10_so_bronze_powder.mag7_cu_mag7_predictor.mag7_gs_mag7_bismuth.mp5sd_gs_mp5_kid_necronomicon.mp7_cu_mp7_fear.mp7_cu_mp7_khaki.mp7_gs_mp7_strone.mp9_aa_mp9_fuji_pink.mp9_gs_mp9_starlight.negev_hy_veneto_tan.p2000_cu_p2k_flying_dream.p2000_p2000_deep_red.p90_am_jorm_blue.r8_sp_spray_water.sawedoff_cu_sawedoff_ouija.scar20_sp_scar_chickenfight.sg553_aa_vertigo.ssg08_cu_ssg_overtake.ssg08_sp_palm_shadow.ump45_gsch_sport_ump45.usps_cu_usp_black_lotus.usps_cu_usp_to_hell.xm1014_am_moro_textile_bright.xm1014_am_xm_zombie_offensive.xm1014_gs_xm1014_watchdog`.split(`.`),
    authentic: `ak47_cu_ak47_nightwish.ak47_gs_ak47_abstract.aug_gs_aug_plague.bizon_cu_bizon_spacecat.bizon_gs_bizon_flasher.deagle_cu_deagle_kitch.dualies_cu_elites_beware.dualies_gs_dual_berettas_tread.famas_cu_famas_spectron.famas_gs_famas_rapid_eyes.fiveseven_cu_fiveseven_alpha_omega.fiveseven_gs_five_seven_efusion.g3sg1_cu_g3sg1_glade.g3sg1_cu_g3sg1_tacticalmap.glock_cu_glock_snackattack.m4a1s_gs_m4a1s_insomnia.m4a4_gs_m4_flowers.mac10_cu_mac10_pixie.mac10_cu_mac10_toybox.mag7_cu_mag7_predictor.mag7_gs_mag7_bismuth.mp5sd_gs_mp5_kid_necronomicon.mp7_cu_mp7_fear.mp7_cu_mp7_khaki.mp9_aa_mp9_fuji_pink.mp9_gs_mp9_starlight.p2000_cu_p2k_flying_dream.sawedoff_cu_sawedoff_ouija.scar20_sp_scar_chickenfight.ssg08_cu_ssg_overtake.usps_cu_usp_black_lotus.usps_cu_usp_to_hell.xm1014_am_xm_zombie_offensive.xm1014_gs_xm1014_watchdog`.split(`.`)
  }, {
    id: `crate_community_30`,
    name: `Dreams & Nightmares Case`,
    set: `set_community_30`,
    decal: `community_30`,
    rare: ``,
    nameKey: `CSGO_set_community_30`,
    price: 250,
    icon: `crate_community_30`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_cogthings.ak47_cu_ak47_nightwish.awp_cu_awp_chroma_pink.awp_gs_independe_awp.bizon_cu_bizon_spacecat.deagle_am_seastorm_blood.dualies_cu_dual_elites_evil_flora.dualies_cu_elites_beware.famas_cu_famas_holo_ocean.famas_gs_famas_corp_meow.famas_gs_famas_rapid_eyes.fiveseven_cu_fiveseven_alpha_omega.g3sg1_cu_g3sg1_glade.g3sg1_sp_mesh_tan.galil_cu_galil_destroyer.glock_gs_glock_elite_camo.glock_hy_ddpat_pink.m249_cu_m249_downvote.m4a1s_gs_m4a1s_insomnia.m4a1s_m4a1s_electrum.m4a4_cu_m4a4_elite_tactical.mac10_cu_mac10_monkeyflage.mac10_cu_mac10_pixie.mac10_so_indigo_and_grey.mag7_cu_mag7_predictor.mp5sd_gs_mp5_kid_necronomicon.mp7_cu_mp7_fear.mp7_hy_ddpat.mp9_gs_mp9_starlight.negev_cu_negev_clear_sky.negev_so_ceramic_negev.p2000_cu_p2k_flying_dream.p2000_so_grassland.p250_gs_p250_visions.p90_am_tigers_brown.p90_gs_p90_tangled.r8_gs_revolver_purple_elite.r8_sp_tape.sawedoff_cu_sawedoff_kisslove.sawedoff_cu_sawedoff_ouija.scar20_sp_scar_chickenfight.sg553_am_army_shine.sg553_cu_sg553_cyber_dragon.ssg08_sp_short_tape.ump45_gs_ump_roadblock.ump45_hy_bloom_red.usps_cu_usp_printstream.usps_cu_usp_to_hell.xm1014_am_nuclear_skulls1_xm1014.xm1014_am_xm_zombie_offensive`.split(`.`),
    authentic: `ak47_cu_ak47_cogthings.ak47_cu_ak47_nightwish.awp_cu_awp_chroma_pink.bizon_cu_bizon_spacecat.dualies_cu_dual_elites_evil_flora.dualies_cu_elites_beware.famas_gs_famas_corp_meow.famas_gs_famas_rapid_eyes.fiveseven_cu_fiveseven_alpha_omega.g3sg1_cu_g3sg1_glade.galil_cu_galil_destroyer.glock_gs_glock_elite_camo.m249_cu_m249_downvote.m4a1s_gs_m4a1s_insomnia.m4a4_cu_m4a4_elite_tactical.mac10_cu_mac10_monkeyflage.mac10_cu_mac10_pixie.mag7_cu_mag7_predictor.mp5sd_gs_mp5_kid_necronomicon.mp7_cu_mp7_fear.mp9_gs_mp9_starlight.negev_cu_negev_clear_sky.p2000_cu_p2k_flying_dream.p250_gs_p250_visions.p90_gs_p90_tangled.r8_gs_revolver_purple_elite.sawedoff_cu_sawedoff_kisslove.sawedoff_cu_sawedoff_ouija.scar20_sp_scar_chickenfight.sg553_cu_sg553_cyber_dragon.ump45_gs_ump_roadblock.usps_cu_usp_printstream.usps_cu_usp_to_hell.xm1014_am_xm_zombie_offensive`.split(`.`)
  }, {
    id: `crate_community_31`,
    name: `Recoil Case`,
    set: `set_community_31`,
    decal: `community_31`,
    rare: ``,
    nameKey: `CSGO_set_community_31`,
    price: 250,
    icon: `crate_community_31`,
    mesh: `csgo`,
    items: `ak47_cu_ak47_cogthings.ak47_cu_ak_head_shot_holo.awp_cu_awp_chroma_pink.awp_gs_awp_limbo_snake.awp_hy_zodiac2.deagle_am_seastorm_shojo.dualies_cu_dual_elites_evil_flora.famas_famas_corp_defense.famas_gs_famas_corp_meow.g3sg1_sp_tape_short_jungle.galil_cu_galil_destroyer.glock_cu_glock_moon_rabbit.glock_gs_glock_elite_camo.glock_hy_leaf_blue.m249_cu_m249_downvote.m4a1s_cu_m4a1s_feeding_frenzy.m4a1s_m4a1s_quick_liquidation.m4a4_cu_m4a4_elite_tactical.m4a4_cu_m4a4_temukau.mac10_cu_mac10_monkeyflage.mac10_cu_mac10_sakkaku.mac10_so_red.mag7_cu_mag7_insomnia.mp5sd_cu_mp5sd_quick_liquidation.mp7_hy_drywood_green.mp9_cu_mp9_superlight.negev_cu_negev_clear_sky.negev_soe_berry.p2000_cu_p2000_decline.p2000_soe_p2000_grips.p250_cu_p250_rebuilt.p250_gs_p250_visions.p90_am_veneto_red.p90_gs_p90_neoqueen.p90_gs_p90_tangled.r8_gs_r8_banana.r8_gs_revolver_purple_elite.sawedoff_aa_fade_metallic.sawedoff_cu_sawedoff_kisslove.scar20_gs_scar_fragments_black.sg553_an_navy.sg553_cu_sg553_cyber_dragon.sg553_cu_sg553_cyberforce.ssg08_sp_tape_short_jungle.tec9_cu_tec9_freedom.ump45_cu_ump_clutch_kick.ump45_gs_ump_roadblock.ump45_hy_blueprint_bluered.usps_cu_usp_printstream.xm1014_aq_blued`.split(`.`),
    authentic: `ak47_cu_ak47_cogthings.ak47_cu_ak_head_shot_holo.awp_cu_awp_chroma_pink.awp_gs_awp_limbo_snake.dualies_cu_dual_elites_evil_flora.famas_gs_famas_corp_meow.galil_cu_galil_destroyer.glock_cu_glock_moon_rabbit.glock_gs_glock_elite_camo.m249_cu_m249_downvote.m4a1s_cu_m4a1s_feeding_frenzy.m4a4_cu_m4a4_elite_tactical.m4a4_cu_m4a4_temukau.mac10_cu_mac10_monkeyflage.mac10_cu_mac10_sakkaku.mag7_cu_mag7_insomnia.mp5sd_cu_mp5sd_quick_liquidation.mp9_cu_mp9_superlight.negev_cu_negev_clear_sky.p2000_cu_p2000_decline.p250_cu_p250_rebuilt.p250_gs_p250_visions.p90_gs_p90_neoqueen.p90_gs_p90_tangled.r8_gs_r8_banana.r8_gs_revolver_purple_elite.sawedoff_cu_sawedoff_kisslove.scar20_gs_scar_fragments_black.sg553_cu_sg553_cyber_dragon.sg553_cu_sg553_cyberforce.tec9_cu_tec9_freedom.ump45_cu_ump_clutch_kick.ump45_gs_ump_roadblock.usps_cu_usp_printstream`.split(`.`)
  }, {
    id: `crate_community_32`,
    name: `Revolution Case`,
    set: `set_community_32`,
    decal: `community_32`,
    rare: ``,
    nameKey: `CSGO_set_community_32`,
    price: 250,
    icon: `crate_community_32`,
    mesh: `csgo`,
    items: `ak47_ak_porcelain.ak47_cu_ak_head_shot_holo.awp_awp_tempered.awp_gs_awp_limbo_snake.awp_soe_bw_the_end_awp.deagle_aq_deagle_case_hardened_2.dualies_dual_berettas_lethal_grin.famas_gs_gamebred_famas.fiveseven_fiveseven_hybrid.galil_aq_titanium_rainbow_galilar.glock_cu_glock_moon_rabbit.glock_glock_brick_mondrian.glock_hy_nerodia.m4a1s_cu_m4a1s_feeding_frenzy.m4a1s_m4a1s_black_lotus.m4a1s_so_orange_accents.m4a4_cu_m4a4_temukau.m4a4_m4a4_snakebite.mac10_cu_mac10_sakkaku.mac10_mac10_illusion.mac10_so_tornado.mag7_cu_mag7_insomnia.mp5sd_cu_mp5sd_quick_liquidation.mp7_hy_gelpen.mp7_mp7_just_smile.mp9_cu_mp9_superlight.negev_sp_nuclear_pattern3_negev.nova_nova_drakkar.p2000_cu_p2000_decline.p2000_soe_teal_glitter.p250_cu_p250_rebuilt.p90_cu_brown_leather_p90.p90_gs_p90_neoqueen.r8_gs_r8_banana.sawedoff_aa_vertigo_red.sawedoff_sawedoff_gamer.scar20_gs_scar_fragments_black.sg553_aq_damascus_sg553.sg553_cu_sg553_cyberforce.ssg08_sp_zebracam_red.ssg08_ssg08_dezastre.tec9_cu_tec9_freedom.tec9_tec9_junkyard_engineering.ump45_cu_ump_clutch_kick.ump45_hy_ddpat_urb.ump45_ump45_assembled_engine.usps_usps_doggy.xm1014_cu_leather_xm1014.xm1014_xm1014_irezumi.zeus_zeus_thunder_god`.split(`.`),
    authentic: `ak47_ak_porcelain.ak47_cu_ak_head_shot_holo.awp_awp_tempered.awp_gs_awp_limbo_snake.dualies_dual_berettas_lethal_grin.fiveseven_fiveseven_hybrid.glock_cu_glock_moon_rabbit.glock_glock_brick_mondrian.m4a1s_cu_m4a1s_feeding_frenzy.m4a1s_m4a1s_black_lotus.m4a4_cu_m4a4_temukau.m4a4_m4a4_snakebite.mac10_cu_mac10_sakkaku.mac10_mac10_illusion.mag7_cu_mag7_insomnia.mp5sd_cu_mp5sd_quick_liquidation.mp7_mp7_just_smile.mp9_cu_mp9_superlight.nova_nova_drakkar.p2000_cu_p2000_decline.p250_cu_p250_rebuilt.p90_gs_p90_neoqueen.r8_gs_r8_banana.sawedoff_sawedoff_gamer.scar20_gs_scar_fragments_black.sg553_cu_sg553_cyberforce.ssg08_ssg08_dezastre.tec9_cu_tec9_freedom.tec9_tec9_junkyard_engineering.ump45_cu_ump_clutch_kick.ump45_ump45_assembled_engine.usps_usps_doggy.xm1014_xm1014_irezumi.zeus_zeus_thunder_god`.split(`.`)
  }, {
    id: `crate_community_33`,
    name: `Kilowatt Case`,
    set: `set_community_33`,
    decal: `community_33`,
    rare: `crate_community_33`,
    nameKey: `CSGO_set_community_33`,
    price: 250,
    icon: `crate_community_33`,
    mesh: `cs2`,
    items: `ak47_ak47_t_bus.ak47_ak_porcelain.aug_aug_puffer.awp_awp_tempered.awp_sp_mesh_tan.deagle_aq_handcannon.deagle_deagle_calligraff.dualies_dual_berettas_lethal_grin.dualies_dual_elite_hydro_strike.famas_ht_splash_famas.fiveseven_fiveseven_hybrid.galil_cu_cerbrus_galil.glock_glock_brick_mondrian.glock_glock_chomper.glock_hye_topo.m249_m249_hypnosis.m4a1s_m4a1s_black_lotus.m4a1s_m4a1s_vaporwave.m4a1s_soch_mountains_m4a1s.m4a4_m4a4_fusion.m4a4_m4a4_snakebite.mac10_mac10_illusion.mac10_mac10_ozaki.mac10_soo_mac10_blueberry.mp5sd_mp5_statics_blue.mp7_hy_plaid1.mp7_mp7_just_smile.negev_sp_palm_bravo.nova_nova_drakkar.p2000_sp_labyrinth2.p250_p250_impact.p90_cu_jaguar_p90.p90_p90_randy_rush.r8_r8_roses_and_guns.sawedoff_aq_copper.sawedoff_sawedoff_gamer.scar20_scar20_fury_topo.sg553_cu_luggage_sg553.ssg08_ssg08_dezastre.ssg08_ssg08_transit_white.tec9_am_crystallized.tec9_tec9_junkyard_engineering.ump45_hy_gelpen.ump45_ump45_assembled_engine.ump45_ump45_neo_noir.usps_usp_field_snake.usps_usps_doggy.xm1014_cu_overpass_monsters_xm.xm1014_xm1014_irezumi.zeus_zeus_thunder_god`.split(`.`),
    authentic: `ak47_ak47_t_bus.ak47_ak_porcelain.aug_aug_puffer.awp_awp_tempered.deagle_deagle_calligraff.dualies_dual_berettas_lethal_grin.dualies_dual_elite_hydro_strike.fiveseven_fiveseven_hybrid.glock_glock_brick_mondrian.glock_glock_chomper.m249_m249_hypnosis.m4a1s_m4a1s_black_lotus.m4a1s_m4a1s_vaporwave.m4a4_m4a4_fusion.m4a4_m4a4_snakebite.mac10_mac10_illusion.mac10_mac10_ozaki.mp5sd_mp5_statics_blue.mp7_mp7_just_smile.nova_nova_drakkar.p250_p250_impact.p90_p90_randy_rush.r8_r8_roses_and_guns.sawedoff_sawedoff_gamer.scar20_scar20_fury_topo.ssg08_ssg08_dezastre.ssg08_ssg08_transit_white.tec9_tec9_junkyard_engineering.ump45_ump45_assembled_engine.ump45_ump45_neo_noir.usps_usp_field_snake.usps_usps_doggy.xm1014_xm1014_irezumi.zeus_zeus_thunder_god`.split(`.`)
  }, {
    id: `crate_community_34`,
    name: `Gallery Case`,
    set: `set_community_34`,
    decal: `community_34`,
    rare: ``,
    nameKey: `CSGO_set_community_34`,
    price: 250,
    icon: `crate_community_34`,
    mesh: `cs2`,
    items: `ak47_ak47_explosive.ak47_ak47_t_bus.aug_aug_puffer.awp_awp_printstream.bizon_aa_wiring.deagle_aq_pilot_deagle.deagle_deagle_calligraff.deagle_deagle_snake_pattern.dualies_dual_elite_hydro_strike.famas_famas_badtrip.famas_hy_reef.galil_cu_poly_green_galil.galil_galil_control_strike.glock_glock_chomper.glock_glock_shinobu.glock_so_night.m249_m249_hypnosis.m4a1s_m4a1s_vaporwave.m4a4_am_circuitboard_silver.m4a4_m4a4_fusion.m4a4_m4a4_green_camo.mac10_mac10_ozaki.mac10_sp_mirage_flowers_tan.mag7_mag7_ammo_box.mp5sd_mp5_statics_blue.mp7_hye_paisley_warm.mp9_mp9_nexus.nova_am_army_shine.nova_nova_rising_sun.p2000_p2k_fractal.p2000_sp_leaves_grassland.p250_p250_impact.p90_cu_p90-asiimov.p90_p90_boost_blue.p90_p90_randy_rush.r8_r8_roses_and_guns.sawedoff_aq_sawed-off_flower.scar20_scar20_fury_topo.sg553_cu_sg553_caution.ssg08_ssg08_brutalist.ssg08_ssg08_transit_white.tec9_am_ossify.ump45_hy_houndstooth_brown.ump45_ump45_neo_noir.ump45_ump45_old_cartoon.usps_usp_field_snake.usps_usps_bruteforce_green.xm1014_cu_xm1014_pharaoh.xm1014_xm1014_mockingbird.zeus_zeus_tosai`.split(`.`),
    authentic: `ak47_ak47_explosive.ak47_ak47_t_bus.aug_aug_puffer.awp_awp_printstream.deagle_deagle_calligraff.deagle_deagle_snake_pattern.dualies_dual_elite_hydro_strike.famas_famas_badtrip.galil_galil_control_strike.glock_glock_chomper.glock_glock_shinobu.m249_m249_hypnosis.m4a1s_m4a1s_vaporwave.m4a4_m4a4_fusion.m4a4_m4a4_green_camo.mac10_mac10_ozaki.mag7_mag7_ammo_box.mp5sd_mp5_statics_blue.mp9_mp9_nexus.nova_nova_rising_sun.p2000_p2k_fractal.p250_p250_impact.p90_p90_boost_blue.p90_p90_randy_rush.r8_r8_roses_and_guns.scar20_scar20_fury_topo.ssg08_ssg08_brutalist.ssg08_ssg08_transit_white.ump45_ump45_neo_noir.ump45_ump45_old_cartoon.usps_usp_field_snake.usps_usps_bruteforce_green.xm1014_xm1014_mockingbird.zeus_zeus_tosai`.split(`.`)
  }, {
    id: `crate_community_35`,
    name: `Fever Case`,
    set: `set_community_35`,
    decal: `community_35`,
    rare: `crate_community_35`,
    nameKey: `CSGO_set_community_35`,
    price: 250,
    icon: `crate_community_35`,
    mesh: `cs2`,
    items: `ak47_ak47_explosive.awp_awp_printstream.bizon_am_carbon_fiber.deagle_cu_glitter_deagle.deagle_deagle_snake_pattern.famas_famas_badtrip.famas_hy_varicamo_desert.galil_galil_control_strike.galil_galil_galigator.glock_glock_shinobu.glock_so_olive.m4a4_am_kimono_sunrise.m4a4_m4a4_green_camo.mac10_sp_palm.mag7_mag7_ammo_box.mp7_mp7_amberline.mp9_mp9_nexus.nova_am_crystallized.nova_gs_ripple_nova.nova_hy_hunter_blaze_orange.nova_hy_hunter_modern.nova_nova_rising_sun.p2000_p2k_fractal.p2000_spe_scarf_print.p90_cu_p90_scarab_of_wisdom.p90_p90_boost_blue.sawedoff_aq_steel.sg553_cu_sg553_rally.ssg08_ssg08_brutalist.tec9_aq_brass.ump45_hy_mottled_sand.ump45_ump45_old_cartoon.usps_usps_bruteforce_green.xm1014_ht_copper_edges.xm1014_xm1014_mockingbird.zeus_zeus_tosai`.split(`.`),
    authentic: [`ak47_ak47_explosive`, `awp_awp_printstream`, `deagle_deagle_snake_pattern`, `famas_famas_badtrip`, `galil_galil_control_strike`, `glock_glock_shinobu`, `m4a4_m4a4_green_camo`, `mag7_mag7_ammo_box`, `mp9_mp9_nexus`, `nova_nova_rising_sun`, `p2000_p2k_fractal`, `p90_p90_boost_blue`, `ssg08_ssg08_brutalist`, `ump45_ump45_old_cartoon`, `usps_usps_bruteforce_green`, `xm1014_xm1014_mockingbird`, `zeus_zeus_tosai`]
  }];
